$(call PKG_INIT_BIN, 1.0)
### WEBSITE:=https://github.com/mandy321/Audiocular-Aura
### CHANGES:=
### CVSREPO:=

$(PKG)_CATEGORY:=Flasher tools

$(PKG)_DEPENDS_ON += hidapi
$(PKG)_DEPENDS_ON += ncurses

$(PKG)_BINARY_BUILD:=$($(PKG)_DIR)/ja11-config-tui
$(PKG)_BINARY_TARGET:=$($(PKG)_DEST_DIR)/usr/bin/ja11-config-tui

$(PKG)_BINARY_JA11BOOT_BUILD:=$($(PKG)_DIR)/ja11-boot
$(PKG)_BINARY_JA11BOOT_TARGET:=$($(PKG)_DEST_DIR)/usr/bin/ja11-boot

$(PKG)_BINARY_JA11FLASH_BUILD:=$($(PKG)_DIR)/ja11-flash
$(PKG)_BINARY_JA11FLASH_TARGET:=$($(PKG)_DEST_DIR)/usr/bin/ja11-flash

$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_JA11_CONFIG

$(PKG_LOCALSOURCE_PACKAGE)
$(PKG_CONFIGURED_NOP)

$($(PKG)_BINARY_BUILD): $($(PKG)_DIR)/.configured
	$(MAKE_ENV) $(TARGET_CC) $(TARGET_CFLAGS) $(TARGET_CPPFLAGS) $(TARGET_LDFLAGS) \
		-Wall -Wextra -Os -std=c11 \
		-D_DEFAULT_SOURCE -D_GNU_SOURCE \
		$(JA11_CONFIG_DIR)/ja11-config-tui.c \
		-o $@ \
		-lhidapi-libusb -lncurses -lm

$($(PKG)_BINARY_JA11BOOT_BUILD): $($(PKG)_DIR)/.configured
	$(MAKE_ENV) $(TARGET_CC) $(TARGET_CFLAGS) $(TARGET_CPPFLAGS) $(TARGET_LDFLAGS) \
		-Wall -Wextra -Os -std=c11 \
		-D_DEFAULT_SOURCE -D_GNU_SOURCE \
		$(JA11_CONFIG_DIR)/ja11-boot.c \
		-o $@ \
		-lhidapi-libusb

$($(PKG)_BINARY_JA11FLASH_BUILD): $($(PKG)_DIR)/.configured
	$(MAKE_ENV) $(TARGET_CC) $(TARGET_CFLAGS) $(TARGET_CPPFLAGS) $(TARGET_LDFLAGS) \
		-Wall -Wextra -Os -std=c11 \
		-D_DEFAULT_SOURCE -D_GNU_SOURCE \
		$(JA11_CONFIG_DIR)/ja11-flash.c \
		-o $@

$($(PKG)_BINARY_TARGET): $($(PKG)_BINARY_BUILD)
	$(INSTALL_BINARY_STRIP)

$($(PKG)_BINARY_JA11BOOT_TARGET): $($(PKG)_BINARY_JA11BOOT_BUILD)
	$(INSTALL_BINARY_STRIP)

$($(PKG)_BINARY_JA11FLASH_TARGET): $($(PKG)_BINARY_JA11FLASH_BUILD)
	$(INSTALL_BINARY_STRIP)

$(pkg):

$(pkg)-precompiled: $($(PKG)_BINARY_TARGET) $($(PKG)_BINARY_JA11BOOT_TARGET) $($(PKG)_BINARY_JA11FLASH_TARGET)

$(pkg)-clean:
	$(RM) $($(PKG)_BINARY_BUILD) $($(PKG)_BINARY_JA11BOOT_BUILD) $($(PKG)_BINARY_JA11FLASH_BUILD)

$(pkg)-uninstall:
	$(RM) $($(PKG)_BINARY_TARGET) $($(PKG)_BINARY_JA11BOOT_TARGET) $($(PKG)_BINARY_JA11FLASH_TARGET)

$(PKG_FINISH)
