$(call PKG_INIT_LIB, 0.2.2)
$(PKG)_LIB_VERSION:=0.2.2
$(PKG)_SOURCE_DOWNLOAD_NAME:=$($(PKG)_VERSION).tar.gz
$(PKG)_SOURCE:=$(pkg)-$($(PKG)_VERSION).tar.gz
$(PKG)_HASH:=16e881487f184250deb4fcb60432d7556ab12cb58caea71ef23960aec6c0405a
$(PKG)_SITE:=https://github.com/libsndfile/libsamplerate/archive/refs/tags
### WEBSITE:=https://libsndfile.github.io/libsamplerate/

$(PKG)_CATEGORY_LIBS:=Multimedia##Audio codecs
$(PKG)_BINARY:=$($(PKG)_DIR)/src/libsamplerate.so.$($(PKG)_LIB_VERSION)
$(PKG)_STAGING_BINARY:=$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libsamplerate.so.$($(PKG)_LIB_VERSION)
$(PKG)_TARGET_BINARY:=$($(PKG)_TARGET_DIR)/libsamplerate.so.$($(PKG)_LIB_VERSION)

$(PKG)_DEPENDS_ON += cmake-host

$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_INSTALL_PREFIX="/usr"
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_BUILD_TYPE=Release
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_SKIP_RPATH=YES
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_POLICY_VERSION_MINIMUM=3.5
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_SHARED_LIBS=ON
$(PKG)_CONFIGURE_OPTIONS += -DLIBSAMPLERATE_TESTS=OFF
$(PKG)_CONFIGURE_OPTIONS += -DLIBSAMPLERATE_EXAMPLES=OFF
$(PKG)_CONFIGURE_OPTIONS += -DLIBSAMPLERATE_FFTW=OFF
$(PKG)_CONFIGURE_OPTIONS += -DLIBSAMPLERATE_MSVC=OFF
$(PKG)_CONFIGURE_OPTIONS += -DLIBSAMPLERATE_STATIC=OFF
$(PKG)_CONFIGURE_OPTIONS += -DLIBSAMPLERATE_STATIC_LIB=OFF

$(PKG_SOURCE_DOWNLOAD)
$(PKG_UNPACKED)
$(PKG_CONFIGURED_CMAKE)

$($(PKG)_BINARY): $($(PKG)_DIR)/.configured
	$(SUBMAKE) -C $(LIBSAMPLERATE_DIR)

$($(PKG)_STAGING_BINARY): $($(PKG)_BINARY)
	$(SUBMAKE) -C $(LIBSAMPLERATE_DIR) \
		DESTDIR="$(TARGET_TOOLCHAIN_STAGING_DIR)" \
		install
	@touch $@

$($(PKG)_TARGET_BINARY): $($(PKG)_STAGING_BINARY)
	$(INSTALL_LIBRARY_STRIP)

$(pkg): $($(PKG)_STAGING_BINARY)

$(pkg)-precompiled: $($(PKG)_TARGET_BINARY)

$(pkg)-clean:
	-$(SUBMAKE) -C $(LIBSAMPLERATE_DIR) clean

$(pkg)-uninstall:
	$(RM) $($(PKG)_TARGET_DIR)/libsamplerate.so*

$(PKG_FINISH)
