$(call PKG_INIT_BIN, 0.35.0)
$(PKG)_SOURCE_DOWNLOAD_NAME:=v$($(PKG)_VERSION).tar.gz
$(PKG)_SOURCE:=$(pkg)-$($(PKG)_VERSION).tar.gz
$(PKG)_HASH:=cb75a71479bf52910bf5f47ae8120ec41c89459b0d77d7cd560e674e437ef050
$(PKG)_SITE:=https://github.com/badaix/snapcast/archive/refs/tags
### WEBSITE:=https://github.com/badaix/snapcast
### MANPAGE:=https://github.com/badaix/snapcast#readme
### CHANGES:=https://github.com/badaix/snapcast/releases
### CVSREPO:=https://github.com/badaix/snapcast
### STEWARD:=Ircama
### PKGSITE:=https://github.com/Ircama/freetz-evo/tree/master/make/pkgs/snapcast/

$(PKG)_CATEGORY_PKGS:=Audio

SNAPCAST_BOOST_VERSION:=1.87.0
SNAPCAST_BOOST_SOURCE:=boost_1_87_0.tar.bz2
SNAPCAST_BOOST_HASH:=af57be25cb4c4f4b413ed692fe378affb4352ea50fbe294a11ef548f4d527d89
SNAPCAST_BOOST_SITE:=https://archives.boost.io/release/$(SNAPCAST_BOOST_VERSION)/source
SNAPCAST_BOOST_ROOT:=$(SNAPCAST_DIR)/.boost/boost_1_87_0
SNAPCAST_BOOST_MARKER:=$(SNAPCAST_BOOST_ROOT)/.unpacked

$(PKG)_BUILD_DIR:=$($(PKG)_DIR)/builddir

SNAPCAST_PKG_DEST_DIR := $($(PKG)_DEST_DIR)
SNAPCAST_TARGET_SERVER := $(SNAPCAST_PKG_DEST_DIR)/usr/bin/snapserver
SNAPCAST_TARGET_CLIENT := $(SNAPCAST_PKG_DEST_DIR)/usr/bin/snapclient
SNAPCAST_TARGET_CONFIG := $(SNAPCAST_PKG_DEST_DIR)/etc/snapserver.conf
SNAPCAST_TARGET_MARKER := $(SNAPCAST_TARGET_SERVER)
SNAPCAST_PKG_CONFIG_DIR := $(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/pkgconfig:$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/share/pkgconfig:$(TARGET_MAKE_PATH)/../lib/pkgconfig

$(PKG)_DEPENDS_ON += cmake-host $(STDCXXLIB)
$(PKG)_DEPENDS_ON += alsa-lib flac libatomic libogg libvorbis openssl

$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_BUILD_TYPE=Release
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_INSTALL_PREFIX=/usr
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_INSTALL_SYSCONFDIR=/etc
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_SKIP_RPATH=YES
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_C_COMPILER="$(TARGET_CC)"
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_CXX_COMPILER="$(TARGET_CXX)"
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_AR="$(TARGET_AR)"
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_RANLIB="$(TARGET_RANLIB)"
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_STRIP="$(TARGET_STRIP)"
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_SYSTEM_NAME=Linux
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_SYSTEM_PROCESSOR=$(FREETZ_TARGET_ARCH)
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_FIND_ROOT_PATH="$(TARGET_TOOLCHAIN_STAGING_DIR)"
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ONLY
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_C_FLAGS="$(TARGET_CFLAGS)"
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_CXX_FLAGS="$(TARGET_CFLAGS)"
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_EXE_LINKER_FLAGS="$(TARGET_LDFLAGS)"
$(PKG)_CONFIGURE_OPTIONS += -DBOOST_ROOT="$(abspath $(SNAPCAST_BOOST_ROOT))"
$(PKG)_CONFIGURE_OPTIONS += -DBoost_INCLUDE_DIR="$(abspath $(SNAPCAST_BOOST_ROOT))"
$(PKG)_CONFIGURE_OPTIONS += -DBoost_NO_SYSTEM_PATHS=ON
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_SHARED_LIBS=OFF
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_STATIC_LIBS=ON
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_TESTS=OFF
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_SERVER=ON
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_CLIENT=ON
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_WITH_SSL=ON
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_WITH_ALSA=ON
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_WITH_FLAC=ON
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_WITH_VORBIS=ON
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_WITH_TREMOR=OFF
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_WITH_OPUS=OFF
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_WITH_AVAHI=OFF
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_WITH_EXPAT=OFF
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_WITH_PULSE=OFF
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_WITH_JACK=OFF
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_WITH_PIPEWIRE=OFF
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_WITH_SDL2=OFF

$(PKG_SOURCE_DOWNLOAD)
$(PKG_UNPACKED)

$(DL_DIR)/$(SNAPCAST_BOOST_SOURCE): | $(DL_DIR)
	$(DL_TOOL) -o $(SNAPCAST_BOOST_SOURCE) $(DL_DIR) $(SNAPCAST_BOOST_SOURCE) $(SNAPCAST_BOOST_SITE) $(SNAPCAST_BOOST_HASH)

$(SNAPCAST_BOOST_MARKER): $(DL_DIR)/$(SNAPCAST_BOOST_SOURCE) $($(PKG)_DIR)/.unpacked
	$(RM) -r $(SNAPCAST_DIR)/.boost
	mkdir -p $(SNAPCAST_DIR)/.boost
	$(call UNPACK_TARBALL,$<,$(SNAPCAST_DIR)/.boost)
	@touch $@

$($(PKG)_DIR)/.configured: $($(PKG)_DIR)/.build-prereq-checked $($(PKG)_DIR)/.unpacked $(SNAPCAST_BOOST_MARKER)
	@$(call _ECHO,configuring)
	cd $(SNAPCAST_DIR); \
		rm -rf builddir; \
		mkdir -p builddir; \
		cd builddir; \
		$(MAKE_ENV) \
		PKG_CONFIG=/usr/bin/pkg-config \
		PKG_CONFIG_PATH="$(SNAPCAST_PKG_CONFIG_DIR)" \
		PKG_CONFIG_LIBDIR="$(SNAPCAST_PKG_CONFIG_DIR)" \
		PKG_CONFIG_SYSROOT_DIR="$(TARGET_TOOLCHAIN_STAGING_DIR)" \
		$(CMAKE) .. \
		$(SNAPCAST_CONFIGURE_OPTIONS) \
		$(SILENT)
	@touch $@

$(SNAPCAST_TARGET_MARKER): $(SNAPCAST_DIR)/.configured
	$(SUBMAKE) -C $(SNAPCAST_BUILD_DIR)
	$(SUBMAKE) -C $(SNAPCAST_BUILD_DIR) DESTDIR="$(abspath $(SNAPCAST_DEST_DIR))" install
	$(RM) -r \
		$(SNAPCAST_DEST_DIR)/usr/share/man \
		$(SNAPCAST_DEST_DIR)/usr/share/pixmaps
	$(TARGET_STRIP) $(SNAPCAST_TARGET_SERVER) 2>/dev/null || true
	$(TARGET_STRIP) $(SNAPCAST_TARGET_CLIENT) 2>/dev/null || true
	@touch $@

$(pkg):

$(pkg)-precompiled: $(SNAPCAST_TARGET_MARKER)

$(pkg)-clean:
	-$(SUBMAKE) -C $(SNAPCAST_BUILD_DIR) clean
	$(RM) -r $(SNAPCAST_BUILD_DIR) $(SNAPCAST_DIR)/.boost $(SNAPCAST_DIR)/.configured

$(pkg)-uninstall:
	$(RM) -r \
		$(SNAPCAST_DEST_DIR)/usr/bin/snapserver \
		$(SNAPCAST_DEST_DIR)/usr/bin/snapclient \
		$(SNAPCAST_DEST_DIR)/etc/snapserver.conf \
		$(SNAPCAST_DEST_DIR)/etc/snapserver \
		$(SNAPCAST_DEST_DIR)/usr/share/snapserver

$(PKG_FINISH)