$(call PKG_INIT_BIN, 1.27.0)
# Requires GCC 8 or newer (FREETZ_TARGET_GCC_8_MIN in Config.in): the unix
# port Makefile uses -Wfloat-conversion (GCC 4.9+) and the CFLAGS_EXTRA below
# adds -Wno-stringop-overflow (GCC 8+). The old GCC 4.6.4 toolchain rejects
# both flags ("cc1: error: unrecognized command line option"), failing the
# qstr header generation step. NOT a uClibc gate: uClibc 1.0.14 with GCC 5.5
# would also fail on -Wno-stringop-overflow, so a uClibc gate would be wrong;
# the GCC gate keeps uClibc >= 1.0.58 (GCC 13.4) working with no regression.
$(PKG)_SOURCE:=$(pkg)-$($(PKG)_VERSION).tar.xz
$(PKG)_HASH:=9874b20646c3bbe81d524f779a16875e5d088b7065e175ffd2aa2a02f50573c9
$(PKG)_SITE:=https://github.com/micropython/micropython/releases/download/v$($(PKG)_VERSION)
### WEBSITE:=https://micropython.org/
### MANPAGE:=https://docs.micropython.org/en/latest/
### CHANGES:=https://github.com/micropython/micropython/releases
### CVSREPO:=https://github.com/micropython/micropython
### STEWARD:=Ircama

# Main interpreter binary (unix port)
$(PKG)_BINARY:=$($(PKG)_DIR)/ports/unix/build-freetz/micropython
$(PKG)_TARGET_BINARY:=$($(PKG)_DEST_DIR)/usr/bin/micropython

# Optional mpy-cross bytecode compiler (cross-compiled for the target device)
$(PKG)_MPYCROSS_BINARY:=$($(PKG)_DIR)/mpy-cross/build-freetz/mpy-cross
$(PKG)_TARGET_MPYCROSS_BINARY:=$($(PKG)_DEST_DIR)/usr/bin/mpy-cross

# micropython-lib module sources and target lib directory
$(PKG)_MPY_LIB_DIR:=$($(PKG)_DIR)/lib/micropython-lib
$(PKG)_TARGET_LIB_DIR:=$($(PKG)_DEST_DIR)/usr/lib/micropython
$(PKG)_MODULES_STAMP:=$($(PKG)_DIR)/.modules_installed

# --- Computed options ---------------------------------------------------------

$(PKG)_VARIANT:=$(if $(FREETZ_PACKAGE_MICROPYTHON_VARIANT_MINIMAL),minimal,standard)

$(PKG)_FLOAT_IMPL:=$(if $(FREETZ_PACKAGE_MICROPYTHON_FLOAT_NONE),MICROPY_FLOAT_IMPL_NONE,$(if $(FREETZ_PACKAGE_MICROPYTHON_FLOAT_FLOAT),MICROPY_FLOAT_IMPL_FLOAT,MICROPY_FLOAT_IMPL_DOUBLE))

# Extra CFLAGS passed to MicroPython's CFLAGS_EXTRA variable.
# _TIME_BITS=64 is omitted (uClibc incompatibility, see patches/).
$(PKG)_CFLAGS_EXTRA:=$(TARGET_CFLAGS) $(FPIC)
$(PKG)_CFLAGS_EXTRA+=-I$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/include
$(PKG)_CFLAGS_EXTRA+=-DMICROPY_FLOAT_IMPL=$($(PKG)_FLOAT_IMPL)
$(PKG)_CFLAGS_EXTRA+=-Wno-stringop-overflow
# Disable btree unless explicitly requested (avoids berkeley-db cross-build)
$(PKG)_CFLAGS_EXTRA+=$(if $(FREETZ_PACKAGE_MICROPYTHON_BTREE),,-DMICROPY_PY_BTREE=0)

# --- Dependencies -------------------------------------------------------------

$(PKG)_DEPENDS_ON+=$(if $(FREETZ_PACKAGE_MICROPYTHON_READLINE),ncurses readline)
# The unix port only adds -lffi when pkg-config finds libffi.pc, which is NOT
# the case in the freetz build environment (the generic tools/path/pkg-config
# does not see the staging dir). So link against the freetz-packaged libffi
# explicitly when the FFI module is enabled (see LDFLAGS_EXTRA below).
$(PKG)_DEPENDS_ON+=$(if $(FREETZ_PACKAGE_MICROPYTHON_FFI),libffi)

# --- Rebuild subopts (binary-affecting options) --------------------------------

$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_VARIANT_STANDARD
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_VARIANT_MINIMAL
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_FLOAT_DOUBLE
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_FLOAT_FLOAT
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_FLOAT_NONE
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_READLINE
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_THREAD
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_SOCKET
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_BTREE
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_FFI
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MPYCROSS

# --- Rebuild subopts (module options, affect installed .py files) --------------

$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_ABC
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_ARGPARSE
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_BASE64
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_BINASCII
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_BISECT
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_CMD
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_COLLECTIONS
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_CONTEXTLIB
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_COPY
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_CURSES_ASCII
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_DATETIME
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_ERRNO
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_FNMATCH
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_FUNCTOOLS
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_GZIP
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_HASHLIB
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_HEAPQ
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_HMAC
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_HTML
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_INSPECT
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_IO
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_ITERTOOLS
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_KEYWORD
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_LOCALE
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_LOGGING
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_OPERATOR
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_OS
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_PATHLIB
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_PICKLE
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_PKGUTIL
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_PPRINT
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_RANDOM
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_SHUTIL
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_SSL
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_STAT
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_STRING
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_STRUCT
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_TARFILE
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_TEMPFILE
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_TEXTWRAP
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_THREADING
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_TRACEBACK
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_TYPES
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_UNITTEST
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_WARNINGS
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_ZLIB
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_AIOREPL
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_MIP
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_SENML
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_UMQTT
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_UREQUESTS
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_MOD_UPYSH
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_UNIX_FFILIB
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_UNIX_GETOPT
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_UNIX_GLOB
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_UNIX_MACHINE
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_UNIX_SELECT
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_UNIX_SIGNAL
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_UNIX_SQLITE3
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_UNIX_TIME
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_UNIX_TIMEIT
$(PKG)_REBUILD_SUBOPTS+=FREETZ_PACKAGE_MICROPYTHON_UNIX_TTY

# --- Has-modules: is at least one .py module selected? -----------------------

$(PKG)_HAS_MODULES:=$(or \
$(FREETZ_PACKAGE_MICROPYTHON_MOD_ABC),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_ARGPARSE),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_BASE64),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_BINASCII),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_BISECT),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_CMD),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_COLLECTIONS),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_CONTEXTLIB),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_COPY),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_CURSES_ASCII),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_DATETIME),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_ERRNO),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_FNMATCH),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_FUNCTOOLS),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_GZIP),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_HASHLIB),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_HEAPQ),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_HMAC),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_HTML),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_INSPECT),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_IO),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_ITERTOOLS),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_KEYWORD),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_LOCALE),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_LOGGING),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_OPERATOR),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_OS),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_PATHLIB),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_PICKLE),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_PKGUTIL),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_PPRINT),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_RANDOM),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_SHUTIL),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_SSL),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_STAT),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_STRING),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_STRUCT),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_TARFILE),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_TEMPFILE),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_TEXTWRAP),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_THREADING),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_TRACEBACK),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_TYPES),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_UNITTEST),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_WARNINGS),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_ZLIB),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_AIOREPL),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_MIP),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_SENML),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_UMQTT),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_UREQUESTS),\
$(FREETZ_PACKAGE_MICROPYTHON_MOD_UPYSH),\
$(FREETZ_PACKAGE_MICROPYTHON_UNIX_FFILIB),\
$(FREETZ_PACKAGE_MICROPYTHON_UNIX_GETOPT),\
$(FREETZ_PACKAGE_MICROPYTHON_UNIX_GLOB),\
$(FREETZ_PACKAGE_MICROPYTHON_UNIX_MACHINE),\
$(FREETZ_PACKAGE_MICROPYTHON_UNIX_SELECT),\
$(FREETZ_PACKAGE_MICROPYTHON_UNIX_SIGNAL),\
$(FREETZ_PACKAGE_MICROPYTHON_UNIX_SQLITE3),\
$(FREETZ_PACKAGE_MICROPYTHON_UNIX_TIME),\
$(FREETZ_PACKAGE_MICROPYTHON_UNIX_TIMEIT),\
$(FREETZ_PACKAGE_MICROPYTHON_UNIX_TTY))


$(PKG_SOURCE_DOWNLOAD)
$(PKG_UNPACKED)
$(PKG_CONFIGURED_NOP)

# --- Build: micropython unix port ---------------------------------------------
#
# Cross-compilation notes:
#   - Pass CC/AR/STRIP explicitly so TARGET_CC already includes the sysroot.
#   - FROZEN_MANIFEST="" disables frozen-module compilation so mpy-cross (host
#     tool) is not required during the cross-build.
#   - CFLAGS_EXTRA carries TARGET_CFLAGS (arch/ABI flags) plus feature flags.
#   - MICROPY_PY_BTREE=0 is the default; enabled only when the user opts in.
#     lib/berkeley-db-1.xx/ is present in the release tarball but cross-
#     compiling it may need extra attention on MIPS/uClibc toolchains.
#   - _TIME_BITS=64 is removed by patches/current/001-uclibc-remove-time-bits-64.patch

$($(PKG)_BINARY): $($(PKG)_DIR)/.configured
	$(SUBMAKE) -C $(MICROPYTHON_DIR)/ports/unix \
		CC="$(TARGET_CC)" \
		AR="$(TARGET_AR)" \
		STRIP="$(TARGET_STRIP)" \
		CFLAGS_EXTRA="$(MICROPYTHON_CFLAGS_EXTRA)" \
		LDFLAGS_EXTRA="$(TARGET_LDFLAGS) $(if $(FREETZ_PACKAGE_MICROPYTHON_FFI),-lffi)" \
		VARIANT=$(MICROPYTHON_VARIANT) \
		BUILD=build-freetz \
		FROZEN_MANIFEST="" \
		MICROPY_USE_READLINE=$(if $(FREETZ_PACKAGE_MICROPYTHON_READLINE),1,0) \
		MICROPY_PY_THREAD=$(if $(FREETZ_PACKAGE_MICROPYTHON_THREAD),1,0) \
		MICROPY_PY_FFI=$(if $(FREETZ_PACKAGE_MICROPYTHON_FFI),1,0) \
		PYTHON=$(FREETZ_BASE_DIR)/tools/path/python3 \
		all

# --- Build: mpy-cross for target device ---------------------------------------
#
# Builds mpy-cross as a MIPS binary for on-device .py to .mpy compilation.
# This is NOT the host-side mpy-cross; it runs on the FritzBox itself.

$($(PKG)_MPYCROSS_BINARY): $($(PKG)_DIR)/.configured
	$(SUBMAKE) -C $(MICROPYTHON_DIR)/mpy-cross \
		CC="$(TARGET_CC)" \
		AR="$(TARGET_AR)" \
		STRIP="$(TARGET_STRIP)" \
		CFLAGS_EXTRA="$(TARGET_CFLAGS) $(FPIC)" \
		LDFLAGS_EXTRA="$(TARGET_LDFLAGS)" \
		BUILD=build-freetz \
		PYTHON=$(FREETZ_BASE_DIR)/tools/path/python3

# --- Install binary -----------------------------------------------------------

$($(PKG)_TARGET_BINARY): $($(PKG)_BINARY)
	$(INSTALL_BINARY_STRIP)

$($(PKG)_TARGET_MPYCROSS_BINARY): $($(PKG)_MPYCROSS_BINARY)
	$(INSTALL_BINARY_STRIP)

# --- Install micropython-lib modules ------------------------------------------
#
# Modules are installed as plain .py files to /usr/lib/micropython/.
# MicroPython searches this directory when MICROPYPATH includes it.
# Set  export MICROPYPATH=/usr/lib/micropython  in /etc/profile or a rc script.
#
# Path convention in the release tarball:
#   python-stdlib/<mod>/<mod>.py         -- single-file stdlib port
#   python-stdlib/<mod>/<mod>/...        -- package (directory) stdlib port
#   micropython/<mod>/<mod>.py           -- single-file micropython-specific
#   micropython/<mod>/<mod>/...          -- package micropython-specific
#   unix-ffi/<mod>/<mod>.py              -- unix FFI wrapper

$($(PKG)_MODULES_STAMP): $($(PKG)_BINARY)
	mkdir -p $(MICROPYTHON_TARGET_LIB_DIR)
	# python-stdlib: single-file modules
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_ABC),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/abc/abc.py $(MICROPYTHON_TARGET_LIB_DIR)/abc.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_ARGPARSE),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/argparse/argparse.py $(MICROPYTHON_TARGET_LIB_DIR)/argparse.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_BASE64),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/base64/base64.py $(MICROPYTHON_TARGET_LIB_DIR)/base64.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_BINASCII),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/binascii/binascii.py $(MICROPYTHON_TARGET_LIB_DIR)/binascii.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_BISECT),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/bisect/bisect.py $(MICROPYTHON_TARGET_LIB_DIR)/bisect.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_CMD),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/cmd/cmd.py $(MICROPYTHON_TARGET_LIB_DIR)/cmd.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_CONTEXTLIB),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/contextlib/contextlib.py $(MICROPYTHON_TARGET_LIB_DIR)/contextlib.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_COPY),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/copy/copy.py $(MICROPYTHON_TARGET_LIB_DIR)/copy.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_DATETIME),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/datetime/datetime.py $(MICROPYTHON_TARGET_LIB_DIR)/datetime.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_ERRNO),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/errno/errno.py $(MICROPYTHON_TARGET_LIB_DIR)/errno.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_FNMATCH),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/fnmatch/fnmatch.py $(MICROPYTHON_TARGET_LIB_DIR)/fnmatch.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_FUNCTOOLS),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/functools/functools.py $(MICROPYTHON_TARGET_LIB_DIR)/functools.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_GZIP),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/gzip/gzip.py $(MICROPYTHON_TARGET_LIB_DIR)/gzip.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_HEAPQ),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/heapq/heapq.py $(MICROPYTHON_TARGET_LIB_DIR)/heapq.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_HMAC),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/hmac/hmac.py $(MICROPYTHON_TARGET_LIB_DIR)/hmac.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_INSPECT),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/inspect/inspect.py $(MICROPYTHON_TARGET_LIB_DIR)/inspect.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_IO),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/io/io.py $(MICROPYTHON_TARGET_LIB_DIR)/io.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_ITERTOOLS),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/itertools/itertools.py $(MICROPYTHON_TARGET_LIB_DIR)/itertools.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_KEYWORD),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/keyword/keyword.py $(MICROPYTHON_TARGET_LIB_DIR)/keyword.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_LOCALE),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/locale/locale.py $(MICROPYTHON_TARGET_LIB_DIR)/locale.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_OPERATOR),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/operator/operator.py $(MICROPYTHON_TARGET_LIB_DIR)/operator.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_PATHLIB),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/pathlib/pathlib.py $(MICROPYTHON_TARGET_LIB_DIR)/pathlib.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_PICKLE),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/pickle/pickle.py $(MICROPYTHON_TARGET_LIB_DIR)/pickle.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_PKGUTIL),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/pkgutil/pkgutil.py $(MICROPYTHON_TARGET_LIB_DIR)/pkgutil.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_PPRINT),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/pprint/pprint.py $(MICROPYTHON_TARGET_LIB_DIR)/pprint.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_RANDOM),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/random/random.py $(MICROPYTHON_TARGET_LIB_DIR)/random.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_SHUTIL),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/shutil/shutil.py $(MICROPYTHON_TARGET_LIB_DIR)/shutil.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_SSL),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/ssl/ssl.py $(MICROPYTHON_TARGET_LIB_DIR)/ssl.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_STAT),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/stat/stat.py $(MICROPYTHON_TARGET_LIB_DIR)/stat.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_STRING),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/string/string.py $(MICROPYTHON_TARGET_LIB_DIR)/string.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_STRUCT),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/struct/struct.py $(MICROPYTHON_TARGET_LIB_DIR)/struct.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_TARFILE),{ test -f $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/tarfile/tarfile.py && install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/tarfile/tarfile.py $(MICROPYTHON_TARGET_LIB_DIR)/tarfile.py; } 2>/dev/null || true)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_TEMPFILE),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/tempfile/tempfile.py $(MICROPYTHON_TARGET_LIB_DIR)/tempfile.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_TEXTWRAP),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/textwrap/textwrap.py $(MICROPYTHON_TARGET_LIB_DIR)/textwrap.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_THREADING),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/threading/threading.py $(MICROPYTHON_TARGET_LIB_DIR)/threading.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_TRACEBACK),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/traceback/traceback.py $(MICROPYTHON_TARGET_LIB_DIR)/traceback.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_TYPES),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/types/types.py $(MICROPYTHON_TARGET_LIB_DIR)/types.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_WARNINGS),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/warnings/warnings.py $(MICROPYTHON_TARGET_LIB_DIR)/warnings.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_ZLIB),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/zlib/zlib.py $(MICROPYTHON_TARGET_LIB_DIR)/zlib.py)
	# python-stdlib: package (directory) modules
	# collections: core package + defaultdict extension
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_COLLECTIONS),mkdir -p $(MICROPYTHON_TARGET_LIB_DIR)/collections && cp -r $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/collections/collections/. $(MICROPYTHON_TARGET_LIB_DIR)/collections/ && cp -f $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/collections-defaultdict/collections/defaultdict.py $(MICROPYTHON_TARGET_LIB_DIR)/collections/)
	# curses.ascii: nested under curses/
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_CURSES_ASCII),mkdir -p $(MICROPYTHON_TARGET_LIB_DIR)/curses && install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/curses.ascii/curses/ascii.py $(MICROPYTHON_TARGET_LIB_DIR)/curses/ascii.py)
	# hashlib: core + sha224/256/384/512 sub-packages
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_HASHLIB),mkdir -p $(MICROPYTHON_TARGET_LIB_DIR)/hashlib && cp -r $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/hashlib-core/hashlib/. $(MICROPYTHON_TARGET_LIB_DIR)/hashlib/ && for _h in sha224 sha256 sha384 sha512; do test -d $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/hashlib-$$_h && cp -r $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/hashlib-$$_h/hashlib/. $(MICROPYTHON_TARGET_LIB_DIR)/hashlib/ 2>/dev/null || true; done)
	# html: package directory
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_HTML),mkdir -p $(MICROPYTHON_TARGET_LIB_DIR)/html && cp -r $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/html/html/. $(MICROPYTHON_TARGET_LIB_DIR)/html/)
	# logging: package directory
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_LOGGING),mkdir -p $(MICROPYTHON_TARGET_LIB_DIR)/logging && { test -d $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/logging/logging && cp -r $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/logging/logging/. $(MICROPYTHON_TARGET_LIB_DIR)/logging/ || test -f $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/logging/logging.py && cp -f $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/logging/logging.py $(MICROPYTHON_TARGET_LIB_DIR)/logging/__init__.py; } 2>/dev/null || true)
	# os: package + os-path extension
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_OS),mkdir -p $(MICROPYTHON_TARGET_LIB_DIR)/os && cp -r $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/os/os/. $(MICROPYTHON_TARGET_LIB_DIR)/os/ && { test -f $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/os-path/os/path.py && cp -f $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/os-path/os/path.py $(MICROPYTHON_TARGET_LIB_DIR)/os/path.py; } 2>/dev/null || true)
	# unittest: package + unittest-discover extension
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_UNITTEST),mkdir -p $(MICROPYTHON_TARGET_LIB_DIR)/unittest && cp -r $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/unittest/unittest/. $(MICROPYTHON_TARGET_LIB_DIR)/unittest/ && { test -f $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/unittest-discover/unittest/discover.py && cp -f $(MICROPYTHON_MPY_LIB_DIR)/python-stdlib/unittest-discover/unittest/discover.py $(MICROPYTHON_TARGET_LIB_DIR)/unittest/discover.py; } 2>/dev/null || true)
	# micropython-lib: micropython-specific modules
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_AIOREPL),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/micropython/aiorepl/aiorepl.py $(MICROPYTHON_TARGET_LIB_DIR)/aiorepl.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_MIP),mkdir -p $(MICROPYTHON_TARGET_LIB_DIR)/mip && cp -r $(MICROPYTHON_MPY_LIB_DIR)/micropython/mip/mip/. $(MICROPYTHON_TARGET_LIB_DIR)/mip/)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_SENML),mkdir -p $(MICROPYTHON_TARGET_LIB_DIR)/senml && cp -r $(MICROPYTHON_MPY_LIB_DIR)/micropython/senml/senml/. $(MICROPYTHON_TARGET_LIB_DIR)/senml/)
	# umqtt: two modules sharing the umqtt/ namespace
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_UMQTT),mkdir -p $(MICROPYTHON_TARGET_LIB_DIR)/umqtt && install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/micropython/umqtt.simple/umqtt/simple.py $(MICROPYTHON_TARGET_LIB_DIR)/umqtt/simple.py && install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/micropython/umqtt.robust/umqtt/robust.py $(MICROPYTHON_TARGET_LIB_DIR)/umqtt/robust.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_UREQUESTS),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/micropython/urequests/urequests.py $(MICROPYTHON_TARGET_LIB_DIR)/urequests.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_MOD_UPYSH),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/micropython/upysh/upysh.py $(MICROPYTHON_TARGET_LIB_DIR)/upysh.py)
	# micropython-lib: unix-ffi modules (require FFI interpreter support)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_UNIX_FFILIB),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/unix-ffi/ffilib/ffilib.py $(MICROPYTHON_TARGET_LIB_DIR)/ffilib.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_UNIX_GETOPT),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/unix-ffi/getopt/getopt.py $(MICROPYTHON_TARGET_LIB_DIR)/getopt.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_UNIX_GLOB),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/unix-ffi/glob/glob.py $(MICROPYTHON_TARGET_LIB_DIR)/glob.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_UNIX_MACHINE),{ test -f $(MICROPYTHON_MPY_LIB_DIR)/unix-ffi/machine/machine.py && install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/unix-ffi/machine/machine.py $(MICROPYTHON_TARGET_LIB_DIR)/machine.py; } 2>/dev/null || true)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_UNIX_SELECT),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/unix-ffi/select/select.py $(MICROPYTHON_TARGET_LIB_DIR)/select.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_UNIX_SIGNAL),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/unix-ffi/signal/signal.py $(MICROPYTHON_TARGET_LIB_DIR)/signal.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_UNIX_SQLITE3),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/unix-ffi/sqlite3/sqlite3.py $(MICROPYTHON_TARGET_LIB_DIR)/sqlite3.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_UNIX_TIME),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/unix-ffi/time/time.py $(MICROPYTHON_TARGET_LIB_DIR)/time.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_UNIX_TIMEIT),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/unix-ffi/timeit/timeit.py $(MICROPYTHON_TARGET_LIB_DIR)/timeit.py)
	$(if $(FREETZ_PACKAGE_MICROPYTHON_UNIX_TTY),install -Dm644 $(MICROPYTHON_MPY_LIB_DIR)/unix-ffi/tty/tty.py $(MICROPYTHON_TARGET_LIB_DIR)/tty.py)
	touch $@

$(pkg):

$(pkg)-precompiled: $($(PKG)_TARGET_BINARY)
$(pkg)-precompiled: $(if $(FREETZ_PACKAGE_MICROPYTHON_MPYCROSS),$($(PKG)_TARGET_MPYCROSS_BINARY))
$(pkg)-precompiled: $(if $(MICROPYTHON_HAS_MODULES),$($(PKG)_MODULES_STAMP))


$(pkg)-clean:
	-$(SUBMAKE) -C $(MICROPYTHON_DIR)/ports/unix BUILD=build-freetz clean
	-$(SUBMAKE) -C $(MICROPYTHON_DIR)/mpy-cross BUILD=build-freetz clean
	$(RM) $(MICROPYTHON_MODULES_STAMP)

$(pkg)-uninstall:
	$(RM) $(MICROPYTHON_TARGET_BINARY)
	$(RM) $(MICROPYTHON_TARGET_MPYCROSS_BINARY)
	$(RM) -r $(MICROPYTHON_TARGET_LIB_DIR)

$(PKG_FINISH)
