#!/bin/sh

. /usr/lib/libmodcgi.sh
[ -r /etc/options.cfg ] && . /etc/options.cfg


[ -z "$PHP_BIN" ] && [ "$FREETZ_PACKAGE_PHP_cgi" == "y" ] && PHP_BIN="php-cgi"
[ -z "$PHP_BIN" ] && [ "$FREETZ_PACKAGE_PHP_cli" == "y" ] && PHP_BIN="php"

# php-cgi enters "serve a script" mode when *any* CGI environment variable is
# present (REQUEST_METHOD, SERVER_*, HTTP_*, PATH_INFO, ...), printing
# "Security Alert" or "No input file specified" instead of phpinfo(). Run it
# with a clean environment; PATH is passed explicitly because the binary
# lives in /usr/bin (or /mod/external/usr/bin via symlink).
PHP_INFO_CALL="env -i PATH=$PATH \
$PHP_BIN -d zlib.output_compression=Off -d cgi.force_redirect=0"

echo "<h1>$(lang de:"PHP-Info" en:"PHP info")</h1>"
if [ -n "$PHP_BIN" ]; then
	# phpinfo() output is trusted HTML generated by PHP itself; render it
	# instead of escaping it. Strip the CGI "Content-type:" header block
	# (everything up to the first empty line; php-cgi emits CRLF headers,
	# so accept optional \r before the newline).
	$PHP_INFO_CALL -i | sed '1,/^ *\r* *$/d'
else
	echo '<pre id="log" class="log full">'
	echo "$(lang de:"Nessun binario PHP trovato" en:"No PHP binary found")"
	echo '</pre>'
fi

