$(call PKG_INIT_LIB, 2.3)
$(PKG)_LIB_VERSION:=2.3.0
$(PKG)_SOURCE:=$(pkg)-$($(PKG)_VERSION).tar.gz
$(PKG)_HASH:=7349f6fd942418bc7009ebe743eb7c9d055f02921ec56fa436ec25007c47fd38
$(PKG)_SITE:=https://github.com/taglib/taglib/releases/download/v$($(PKG)_VERSION)
### WEBSITE:=https://taglib.org/
### CHANGES:=https://github.com/taglib/taglib/releases
### CVSREPO:=https://github.com/taglib/taglib

$(PKG)_BINARY:=$($(PKG)_DIR)/taglib/libtag.so.$($(PKG)_LIB_VERSION)
$(PKG)_STAGING_BINARY:=$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libtag.so.$($(PKG)_LIB_VERSION)
$(PKG)_TARGET_BINARY:=$($(PKG)_TARGET_DIR)/libtag.so.$($(PKG)_LIB_VERSION)

$(PKG)_DEPENDS_ON += cmake-host
$(PKG)_DEPENDS_ON += $(STDCXXLIB) zlib
$(PKG)_REBUILD_SUBOPTS += FREETZ_STDCXXLIB

$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_INSTALL_PREFIX="/usr"
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_BUILD_TYPE=Release
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_SKIP_RPATH=YES
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_SHARED_LIBS=ON
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_TESTING=OFF
$(PKG)_CONFIGURE_OPTIONS += -DWITH_APE=ON
$(PKG)_CONFIGURE_OPTIONS += -DWITH_ASF=ON
$(PKG)_CONFIGURE_OPTIONS += -DWITH_DSF=ON
$(PKG)_CONFIGURE_OPTIONS += -DWITH_MATROSKA=ON
$(PKG)_CONFIGURE_OPTIONS += -DWITH_MOD=ON
$(PKG)_CONFIGURE_OPTIONS += -DWITH_MP4=ON
$(PKG)_CONFIGURE_OPTIONS += -DWITH_RIFF=ON
$(PKG)_CONFIGURE_OPTIONS += -DWITH_SHORTEN=ON
$(PKG)_CONFIGURE_OPTIONS += -DWITH_TRUEAUDIO=ON
$(PKG)_CONFIGURE_OPTIONS += -DWITH_VORBIS=ON

$(PKG_SOURCE_DOWNLOAD)
$(PKG_UNPACKED)
$(PKG_CONFIGURED_CMAKE)

$($(PKG)_BINARY): $($(PKG)_DIR)/.configured
	$(SUBMAKE) -C $(TAGLIB_DIR)

$($(PKG)_STAGING_BINARY): $($(PKG)_BINARY)
	$(SUBMAKE) -C $(TAGLIB_DIR) \
		DESTDIR="$(TARGET_TOOLCHAIN_STAGING_DIR)" \
		install
	@touch $@

$($(PKG)_TARGET_BINARY): $($(PKG)_STAGING_BINARY)
	$(INSTALL_LIBRARY_STRIP_WILDCARD_BEFORE_SO)

$(pkg): $($(PKG)_STAGING_BINARY)

$(pkg)-precompiled: $($(PKG)_TARGET_BINARY)

$(pkg)-clean:
	-$(SUBMAKE) -C $(TAGLIB_DIR) clean
	$(RM) -r \
		$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/include/taglib \
		$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libtag* \
		$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/pkgconfig/taglib*.pc

$(pkg)-uninstall:
	$(RM) $(TAGLIB_TARGET_DIR)/libtag*.so*

$(PKG_FINISH)
