$(call PKG_INIT_BIN, 0.24.7)
$(PKG)_SOURCE_DOWNLOAD_NAME:=v$($(PKG)_VERSION).tar.gz
$(PKG)_SOURCE:=$(pkg)-$($(PKG)_VERSION).tar.gz
$(PKG)_HASH:=d497c07df2a78600cf60e4a47c677df9cf9ac1daecb3c163147b643a6e2e0882
$(PKG)_SITE:=https://github.com/MusicPlayerDaemon/MPD/archive/refs/tags
### WEBSITE:=https://www.musicpd.org/
### MANPAGE:=https://mpd.readthedocs.io/en/stable/user.html
### CHANGES:=https://github.com/MusicPlayerDaemon/MPD/releases
### CVSREPO:=https://github.com/MusicPlayerDaemon/MPD
### STEWARD:=Ircama
### PKGSITE:=https://github.com/Ircama/freetz-evo/tree/master/make/pkgs/mpd/

$(PKG)_CATEGORY:=Audio

$(PKG)_BINARY:=$($(PKG)_DIR)/builddir/mpd
$(PKG)_TARGET_BINARY:=$($(PKG)_DEST_DIR)/usr/bin/mpd

$(PKG)_DEPENDS_ON += meson-host
$(PKG)_DEPENDS_ON += $(if $(FREETZ_SEPARATE_AVM_UCLIBC),patchelf-target-host)
$(PKG)_DEPENDS_ON += jemalloc
$(PKG)_DEPENDS_ON += alsa-lib flac libid3tag libmad libogg libvorbis zlib
$(PKG)_DEPENDS_ON += $(if $(FREETZ_PACKAGE_MPD_WITH_URI_INPUTS),curl)
$(PKG)_DEPENDS_ON += $(if $(FREETZ_PACKAGE_MPD_WITH_SQLITE),sqlite)
$(PKG)_DEPENDS_ON += $(if $(FREETZ_PACKAGE_MPD_WITH_BZIP2),bzip2)
$(PKG)_DEPENDS_ON += $(if $(FREETZ_PACKAGE_MPD_WITH_FFMPEG),ffmpeg)
$(PKG)_DEPENDS_ON += $(if $(FREETZ_PACKAGE_MPD_WITH_ICU),icu)
$(PKG)_DEPENDS_ON += $(if $(FREETZ_PACKAGE_MPD_WITH_WAVPACK),libwavpack)
$(PKG)_DEPENDS_ON += $(if $(FREETZ_PACKAGE_MPD_WITH_UPNP),libupnp)
$(PKG)_DEPENDS_ON += $(if $(FREETZ_PACKAGE_MPD_WITH_EXPAT),expat)
$(PKG)_DEPENDS_ON += $(if $(FREETZ_PACKAGE_MPD_WITH_OPUS),opus)
$(PKG)_DEPENDS_ON += $(if $(FREETZ_PACKAGE_MPD_WITH_ICONV),iconv)
$(PKG)_DEPENDS_ON += $(if $(FREETZ_PACKAGE_MPD_WITH_VORBISENC),libvorbis)
$(PKG)_DEPENDS_ON += $(if $(FREETZ_PACKAGE_MPD_WITH_FAAD),faad2)
$(PKG)_DEPENDS_ON += $(if $(FREETZ_PACKAGE_MPD_WITH_FLUIDSYNTH),fluidsynth)
$(PKG)_DEPENDS_ON += $(if $(FREETZ_PACKAGE_MPD_WITH_LIBSAMPLERATE),libsamplerate)
$(PKG)_DEPENDS_ON += $(if $(FREETZ_PACKAGE_MPD_WITH_MPG123),mpg123)
$(PKG)_DEPENDS_ON += $(if $(FREETZ_PACKAGE_MPD_WITH_NFS),libnfs)
$(PKG)_DEPENDS_ON += $(if $(FREETZ_PACKAGE_MPD_WITH_SHINE),shine)
$(PKG)_DEPENDS_ON += $(if $(FREETZ_PACKAGE_MPD_WITH_SHOUT),libshout)
$(PKG)_DEPENDS_ON += $(if $(FREETZ_PACKAGE_MPD_WITH_SOXR),soxr)
$(PKG)_DEPENDS_ON += $(if $(FREETZ_PACKAGE_MPD_WITH_TREMOR),tremor)
$(PKG)_DEPENDS_ON += $(if $(FREETZ_PACKAGE_MPD_WITH_WILDMIDI),libwildmidi)

$(PKG)_REBUILD_SUBOPTS += FREETZ_LIB_libjemalloc
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MPD_WITH_URI_INPUTS
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MPD_WITH_SQLITE
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MPD_WITH_BZIP2
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MPD_WITH_FFMPEG
$(PKG)_REBUILD_SUBOPTS += $(if $(FREETZ_PACKAGE_MPD_WITH_FFMPEG),FREETZ_PACKAGE_FFMPEG_VERSION_ABANDON)
$(PKG)_REBUILD_SUBOPTS += $(if $(FREETZ_PACKAGE_MPD_WITH_URI_INPUTS),$(filter FREETZ_LIB_libcurl_%,$(CURL_REBUILD_SUBOPTS)))
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MPD_WITH_ICU
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MPD_WITH_WAVPACK
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MPD_WITH_UPNP
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MPD_WITH_EXPAT
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MPD_WITH_OPUS
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MPD_WITH_ICONV
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MPD_WITH_VORBISENC
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MPD_WITH_IPV6
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MPD_WITH_DSD
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MPD_WITH_CUE
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MPD_WITH_NEIGHBOR
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MPD_WITH_WEBDAV
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MPD_WITH_PIPE
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MPD_WITH_FIFO
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MPD_WITH_HTTPD
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MPD_WITH_FAAD
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MPD_WITH_FLUIDSYNTH
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MPD_WITH_LIBSAMPLERATE
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MPD_WITH_MPG123
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MPD_WITH_NFS
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MPD_WITH_SHINE
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MPD_WITH_SHOUT
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MPD_WITH_SOXR
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MPD_WITH_TREMOR
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MPD_WITH_WILDMIDI

MPD_MESON_ENV := PATH="$(abspath $(TOOLS_DIR)/path):$(subst ",,$(TARGET_PATH))" $(FREETZ_LD_RUN_PATH) FREETZ_LIBRARY_DIR="$(FREETZ_LIBRARY_DIR)"
MPD_EXTRA_LDFLAGS := $(TARGET_LDFLAGS) -L$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib -ljemalloc

$(PKG)_CONFIGURE_ENV += PATH="$(abspath $(TOOLS_DIR)/path):$(subst ",,$(TARGET_PATH))"
$(PKG)_CONFIGURE_ENV += FREETZ_LIBRARY_DIR="$(FREETZ_LIBRARY_DIR)"
$(PKG)_CONFIGURE_ENV += LDFLAGS="$(MPD_EXTRA_LDFLAGS)"

$(PKG)_CONFIGURE_OPTIONS += -Dcpp_args=-DFMT_DEPRECATED_HEAVY_CORE

$(PKG)_CONFIGURE_OPTIONS += -D documentation=disabled
$(PKG)_CONFIGURE_OPTIONS += -D html_manual=false
$(PKG)_CONFIGURE_OPTIONS += -D manpages=false
$(PKG)_CONFIGURE_OPTIONS += -D syslog=disabled
$(PKG)_CONFIGURE_OPTIONS += -D systemd=disabled
$(PKG)_CONFIGURE_OPTIONS += -D dbus=disabled
$(PKG)_CONFIGURE_OPTIONS += -D zeroconf=disabled
$(PKG)_CONFIGURE_OPTIONS += -D sqlite=$(if $(FREETZ_PACKAGE_MPD_WITH_SQLITE),enabled,disabled)
$(PKG)_CONFIGURE_OPTIONS += -D pcre=disabled
$(PKG)_CONFIGURE_OPTIONS += -D icu=$(if $(FREETZ_PACKAGE_MPD_WITH_ICU),enabled,disabled)
$(PKG)_CONFIGURE_OPTIONS += -D iconv=$(if $(FREETZ_PACKAGE_MPD_WITH_ICONV),enabled,disabled)
$(PKG)_CONFIGURE_OPTIONS += -D expat=$(if $(FREETZ_PACKAGE_MPD_WITH_EXPAT),enabled,disabled)
$(PKG)_CONFIGURE_OPTIONS += -D curl=$(if $(FREETZ_PACKAGE_MPD_WITH_URI_INPUTS),enabled,disabled)
$(PKG)_CONFIGURE_OPTIONS += -D webdav=$(if $(FREETZ_PACKAGE_MPD_WITH_WEBDAV),enabled,disabled)
$(PKG)_CONFIGURE_OPTIONS += -D nfs=$(if $(FREETZ_PACKAGE_MPD_WITH_NFS),enabled,disabled)
$(PKG)_CONFIGURE_OPTIONS += -D qobuz=disabled
$(PKG)_CONFIGURE_OPTIONS += -D libmpdclient=disabled
$(PKG)_CONFIGURE_OPTIONS += -D io_uring=disabled
$(PKG)_CONFIGURE_OPTIONS += -D ipv6=$(if $(FREETZ_PACKAGE_MPD_WITH_IPV6),enabled,disabled)
$(PKG)_CONFIGURE_OPTIONS += -D neighbor=$(if $(FREETZ_PACKAGE_MPD_WITH_NEIGHBOR),true,false)
$(PKG)_CONFIGURE_OPTIONS += -D database=true
$(PKG)_CONFIGURE_OPTIONS += -D inotify=true
$(PKG)_CONFIGURE_OPTIONS += -D tcp=true
$(PKG)_CONFIGURE_OPTIONS += -D local_socket=true
$(PKG)_CONFIGURE_OPTIONS += -D daemon=true
$(PKG)_CONFIGURE_OPTIONS += -D dsd=$(if $(FREETZ_PACKAGE_MPD_WITH_DSD),true,false)
$(PKG)_CONFIGURE_OPTIONS += -D cue=$(if $(FREETZ_PACKAGE_MPD_WITH_CUE),true,false)
$(PKG)_CONFIGURE_OPTIONS += -D bzip2=$(if $(FREETZ_PACKAGE_MPD_WITH_BZIP2),enabled,disabled)
$(PKG)_CONFIGURE_OPTIONS += -D iso9660=disabled
$(PKG)_CONFIGURE_OPTIONS += -D zzip=disabled
$(PKG)_CONFIGURE_OPTIONS += -D cdio_paranoia=disabled
$(PKG)_CONFIGURE_OPTIONS += -D upnp=$(if $(FREETZ_PACKAGE_MPD_WITH_UPNP),pupnp,disabled)
$(PKG)_CONFIGURE_OPTIONS += -D smbclient=disabled
$(PKG)_CONFIGURE_OPTIONS += -D id3tag=enabled
$(PKG)_CONFIGURE_OPTIONS += -D flac=enabled
$(PKG)_CONFIGURE_OPTIONS += -D mad=enabled
$(PKG)_CONFIGURE_OPTIONS += -D vorbis=$(if $(FREETZ_PACKAGE_MPD_WITH_TREMOR),disabled,enabled)
$(PKG)_CONFIGURE_OPTIONS += -D adplug=disabled
$(PKG)_CONFIGURE_OPTIONS += -D audiofile=disabled
$(PKG)_CONFIGURE_OPTIONS += -D faad=$(if $(FREETZ_PACKAGE_MPD_WITH_FAAD),enabled,disabled)
$(PKG)_CONFIGURE_OPTIONS += -D ffmpeg=$(if $(FREETZ_PACKAGE_MPD_WITH_FFMPEG),enabled,disabled)
$(PKG)_CONFIGURE_OPTIONS += -D fluidsynth=$(if $(FREETZ_PACKAGE_MPD_WITH_FLUIDSYNTH),enabled,disabled)
$(PKG)_CONFIGURE_OPTIONS += -D gme=disabled
$(PKG)_CONFIGURE_OPTIONS += -D mikmod=disabled
$(PKG)_CONFIGURE_OPTIONS += -D modplug=disabled
$(PKG)_CONFIGURE_OPTIONS += -D openmpt=disabled
$(PKG)_CONFIGURE_OPTIONS += -D mpcdec=disabled
$(PKG)_CONFIGURE_OPTIONS += -D mpg123=$(if $(FREETZ_PACKAGE_MPD_WITH_MPG123),enabled,disabled)
$(PKG)_CONFIGURE_OPTIONS += -D opus=$(if $(FREETZ_PACKAGE_MPD_WITH_OPUS),enabled,disabled)
$(PKG)_CONFIGURE_OPTIONS += -D sidplay=disabled
$(PKG)_CONFIGURE_OPTIONS += -D sndfile=disabled
$(PKG)_CONFIGURE_OPTIONS += -D tremor=$(if $(FREETZ_PACKAGE_MPD_WITH_TREMOR),enabled,disabled)
$(PKG)_CONFIGURE_OPTIONS += -D wavpack=$(if $(FREETZ_PACKAGE_MPD_WITH_WAVPACK),enabled,disabled)
$(PKG)_CONFIGURE_OPTIONS += -D wildmidi=$(if $(FREETZ_PACKAGE_MPD_WITH_WILDMIDI),enabled,disabled)
$(PKG)_CONFIGURE_OPTIONS += -D vorbisenc=$(if $(FREETZ_PACKAGE_MPD_WITH_VORBISENC),$(if $(FREETZ_PACKAGE_MPD_WITH_TREMOR),disabled,enabled),disabled)
$(PKG)_CONFIGURE_OPTIONS += -D lame=disabled
$(PKG)_CONFIGURE_OPTIONS += -D twolame=disabled
$(PKG)_CONFIGURE_OPTIONS += -D shine=$(if $(FREETZ_PACKAGE_MPD_WITH_SHINE),enabled,disabled)
$(PKG)_CONFIGURE_OPTIONS += -D wave_encoder=false
$(PKG)_CONFIGURE_OPTIONS += -D libsamplerate=$(if $(FREETZ_PACKAGE_MPD_WITH_LIBSAMPLERATE),enabled,disabled)
$(PKG)_CONFIGURE_OPTIONS += -D soxr=$(if $(FREETZ_PACKAGE_MPD_WITH_SOXR),enabled,disabled)
$(PKG)_CONFIGURE_OPTIONS += -D alsa=enabled
$(PKG)_CONFIGURE_OPTIONS += -D ao=disabled
$(PKG)_CONFIGURE_OPTIONS += -D fifo=$(if $(FREETZ_PACKAGE_MPD_WITH_FIFO),true,false)
$(PKG)_CONFIGURE_OPTIONS += -D httpd=$(if $(FREETZ_PACKAGE_MPD_WITH_HTTPD),true,false)
$(PKG)_CONFIGURE_OPTIONS += -D jack=disabled
$(PKG)_CONFIGURE_OPTIONS += -D openal=disabled
$(PKG)_CONFIGURE_OPTIONS += -D oss=disabled
$(PKG)_CONFIGURE_OPTIONS += -D pipe=$(if $(FREETZ_PACKAGE_MPD_WITH_PIPE),true,false)
$(PKG)_CONFIGURE_OPTIONS += -D pipewire=disabled
$(PKG)_CONFIGURE_OPTIONS += -D pulse=disabled
$(PKG)_CONFIGURE_OPTIONS += -D recorder=false
$(PKG)_CONFIGURE_OPTIONS += -D shout=$(if $(FREETZ_PACKAGE_MPD_WITH_SHOUT),enabled,disabled)
$(PKG)_CONFIGURE_OPTIONS += -D snapcast=false
$(PKG)_CONFIGURE_OPTIONS += -D sndio=disabled
$(PKG)_CONFIGURE_OPTIONS += -D solaris_output=disabled

$(PKG)_CONFIGURE_PRE_CMDS += $(SED) -r -i \
	-e "s|^pkg-?config[[:space:]]*=.*|pkg-config        = 'pkg-config'|" \
	-e "s|^python[[:space:]]*=.*|python            = '$(abspath $(TOOLS_DIR)/path/python3)'|" \
	-e "s|^cmake[[:space:]]*=.*|cmake             = '$(abspath $(TOOLS_DIR)/path/cmake)'|" \
	meson.freetz;

$(PKG_SOURCE_DOWNLOAD)
$(PKG_UNPACKED)
$(PKG_CONFIGURED_MESON)

$($(PKG)_BINARY): $($(PKG)_DIR)/.configured
	cmd() { $(MPD_MESON_ENV) $(MESON) "$$@" $(SILENT) || { $(call ERROR,1,$(BUILD_FAIL_MSG)) } ; }; $(call _ECHO,building) cmd compile \
		-C $(MPD_DIR)/builddir/

$($(PKG)_TARGET_BINARY): $($(PKG)_BINARY)
	$(INSTALL_BINARY_STRIP)

$(pkg):

$(pkg)-precompiled: $($(PKG)_TARGET_BINARY)

$(pkg)-clean:
	-$(SUBNINJA) -C $(MPD_DIR)/builddir/ clean
	$(RM) $(MPD_DIR)/.configured

$(pkg)-uninstall:
	$(RM) $(MPD_TARGET_BINARY)

$(PKG_FINISH)