$(call PKG_INIT_LIB, 4.3.9)
$(PKG)_SHLIB_VERSION:=19
$(PKG)_SOURCE_DOWNLOAD_NAME:=v$($(PKG)_VERSION).tar.gz
$(PKG)_SOURCE:=$(pkg)-$($(PKG)_VERSION).tar.gz
$(PKG)_HASH:=2c79020cdb053b070ea53e350581d87a6b630f6accd9fb9e3798259c3068caf1
$(PKG)_SITE:=https://github.com/warmcat/libwebsockets/archive/refs/tags
### VERSION:=4.3.9
### WEBSITE:=https://libwebsockets.org/
### MANPAGE:=https://libwebsockets.org/lws-api-doc-master/html/index.html
### CHANGES:=https://github.com/warmcat/libwebsockets/releases
### CVSREPO:=https://github.com/warmcat/libwebsockets

$(PKG)_DEPENDS_ON += cmake-host libuv
$(PKG)_REBUILD_SUBOPTS += FREETZ_LIB_libwebsockets_WITH_SSL

$(PKG)_LIBNAME:=$(pkg).so.$($(PKG)_SHLIB_VERSION)
# libwebsockets sets CMAKE_LIBRARY_OUTPUT_DIRECTORY to ${PROJECT_BINARY_DIR}/lib

$(PKG)_CATEGORY_LIBS:=Web and WebDAV
$(PKG)_BINARY:=$($(PKG)_DIR)/lib/$($(PKG)_LIBNAME)
$(PKG)_STAGING_BINARY:=$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/$($(PKG)_LIBNAME)
$(PKG)_TARGET_BINARY:=$($(PKG)_TARGET_DIR)/$($(PKG)_LIBNAME)

$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_INSTALL_PREFIX="/usr"
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_SKIP_RPATH=YES
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_BUILD_TYPE=Release
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_POLICY_VERSION_MINIMUM=3.5
$(PKG)_CONFIGURE_OPTIONS += -DDISABLE_WERROR=ON

# libuv event loop integration (required by ttyd)
$(PKG)_CONFIGURE_OPTIONS += -DLWS_WITH_LIBUV=ON
$(PKG)_CONFIGURE_OPTIONS += -DLWS_WITH_EVLIB_PLUGINS=OFF
$(PKG)_CONFIGURE_OPTIONS += -DLIBUV_INCLUDE_DIR="$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/include"
$(PKG)_CONFIGURE_OPTIONS += -DLIBUV_LIBRARIES="$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libuv.so"

# SSL support
ifeq ($(strip $(FREETZ_LIB_libwebsockets_WITH_SSL)),y)
$(PKG)_CONFIGURE_OPTIONS += -DLWS_WITH_SSL=ON
$(PKG)_CONFIGURE_OPTIONS += -DLWS_WITH_MBEDTLS=OFF
$(PKG)_CONFIGURE_OPTIONS += -DOPENSSL_INCLUDE_DIR="$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/include"
$(PKG)_CONFIGURE_OPTIONS += -DOPENSSL_SSL_LIBRARY="$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libssl.so"
$(PKG)_CONFIGURE_OPTIONS += -DOPENSSL_CRYPTO_LIBRARY="$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libcrypto.so"
$(PKG)_DEPENDS_ON += openssl
else
$(PKG)_CONFIGURE_OPTIONS += -DLWS_WITH_SSL=OFF
endif

# Build options - minimize size for embedded use
$(PKG)_CONFIGURE_OPTIONS += -DLWS_WITH_SHARED=ON
$(PKG)_CONFIGURE_OPTIONS += -DLWS_WITH_STATIC=OFF
$(PKG)_CONFIGURE_OPTIONS += -DLWS_WITHOUT_TESTAPPS=ON
$(PKG)_CONFIGURE_OPTIONS += -DLWS_WITHOUT_TEST_SERVER=ON
$(PKG)_CONFIGURE_OPTIONS += -DLWS_WITHOUT_TEST_SERVER_EXTPOLL=ON
$(PKG)_CONFIGURE_OPTIONS += -DLWS_WITHOUT_TEST_PING=ON
$(PKG)_CONFIGURE_OPTIONS += -DLWS_WITHOUT_TEST_CLIENT=ON
$(PKG)_CONFIGURE_OPTIONS += -DLWS_WITH_MINIMAL_EXAMPLES=OFF
$(PKG)_CONFIGURE_OPTIONS += -DLWS_WITH_LWSWS=OFF
$(PKG)_CONFIGURE_OPTIONS += -DLWS_WITH_CGI=OFF
$(PKG)_CONFIGURE_OPTIONS += -DLWS_IPV6=OFF
$(PKG)_CONFIGURE_OPTIONS += -DLWS_WITH_HTTP2=ON
$(PKG)_CONFIGURE_OPTIONS += -DLWS_WITHOUT_EXTENSIONS=ON
$(PKG)_CONFIGURE_OPTIONS += -DLWS_WITH_ZIP_FOPS=OFF
$(PKG)_CONFIGURE_OPTIONS += -DLWS_WITHOUT_DAEMONIZE=ON
$(PKG)_CONFIGURE_OPTIONS += -DLWS_WITH_EXPORT_LWSTARGETS=ON
$(PKG)_CONFIGURE_OPTIONS += -DLWS_REPRODUCIBLE=ON


$(PKG_SOURCE_DOWNLOAD)
$(PKG_UNPACKED)
$(PKG_CONFIGURED_CMAKE)

$($(PKG)_BINARY): $($(PKG)_DIR)/.configured
	$(SUBMAKE) -C $(LIBWEBSOCKETS_DIR)

$($(PKG)_STAGING_BINARY): $($(PKG)_BINARY)
	$(SUBMAKE) -C $(LIBWEBSOCKETS_DIR) \
		DESTDIR="$(TARGET_TOOLCHAIN_STAGING_DIR)" \
		install
	@touch $@

$($(PKG)_TARGET_BINARY): $($(PKG)_STAGING_BINARY)
	$(INSTALL_LIBRARY_STRIP)

$(pkg): $($(PKG)_STAGING_BINARY)

$(pkg)-precompiled: $($(PKG)_TARGET_BINARY)


$(pkg)-clean:
	-$(SUBMAKE) -C $(LIBWEBSOCKETS_DIR) clean
	$(RM) -r \
		$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libwebsockets.* \
		$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/include/libwebsockets.h \
		$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/include/lws_config.h \
		$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/include/libwebsockets/ \
		$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/pkgconfig/libwebsockets.pc \
		$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/cmake/libwebsockets/

$(pkg)-uninstall:
	$(RM) $(LIBWEBSOCKETS_TARGET_DIR)/libwebsockets.so*

$(PKG_FINISH)
