# libupnp 1.14.31 sets CMAKE_CXX_STANDARD 14 (REQUIRED ON) in CMakeLists.txt;
# the old GCC 4.6.4 toolchain does not support C++14 -> cmake configure
# fails ("Target ... requires the language dialect \"CXX14\""). The new
# toolchain (GCC 13.4 + uClibc 1.0.58) supports it, hence the
# FREETZ_TARGET_UCLIBC_1_0_58_MIN dependency in Config.in.
$(call PKG_INIT_LIB, 1.14.31)
$(PKG)_LIB_VERSION:=17.2.11
$(PKG)_SOURCE:=$(pkg)-$($(PKG)_VERSION).tar.bz2
$(PKG)_HASH:=e72c7690d5df862c07e9014f99513f5a94b55f80d916120655f73e11863edf3f
$(PKG)_SITE:=https://github.com/pupnp/pupnp/releases/download/release-$($(PKG)_VERSION)
### WEBSITE:=https://pupnp.github.io/pupnp/
### CHANGES:=https://github.com/pupnp/pupnp/releases
### CVSREPO:=https://github.com/pupnp/pupnp

$(PKG)_BINARY:=$($(PKG)_DIR)/upnp/libupnp.so.$($(PKG)_LIB_VERSION)
$(PKG)_STAGING_BINARY:=$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libupnp.so.$($(PKG)_LIB_VERSION)
$(PKG)_TARGET_BINARY:=$($(PKG)_TARGET_DIR)/libupnp.so.$($(PKG)_LIB_VERSION)

$(PKG)_DEPENDS_ON += cmake-host
$(PKG)_DEPENDS_ON += e2fsprogs

$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_INSTALL_PREFIX="/usr"
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_BUILD_TYPE=Release
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_SKIP_RPATH=YES
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_TESTING=OFF
$(PKG)_CONFIGURE_OPTIONS += -DUPNP_BUILD_SAMPLES=OFF
$(PKG)_CONFIGURE_OPTIONS += -DUPNP_ENABLE_OPEN_SSL=OFF
$(PKG)_CONFIGURE_OPTIONS += -DUPNP_ENABLE_IPV6=$(if $(FREETZ_TARGET_IPV6_SUPPORT),ON,OFF)
$(PKG)_CONFIGURE_OPTIONS += -DUPNP_ENABLE_WEBSERVER=ON
$(PKG)_CONFIGURE_OPTIONS += -DUPNP_ENABLE_DEVICE_API=ON
$(PKG)_CONFIGURE_OPTIONS += -DUPNP_ENABLE_CLIENT_API=ON
$(PKG)_CONFIGURE_OPTIONS += -DUPNP_MINISERVER_REUSEADDR=ON
$(PKG)_CONFIGURE_OPTIONS += -DUPNP_ENABLE_BLOCKING_TCP_CONNECTIONS=OFF
$(PKG)_CONFIGURE_OPTIONS += -DIXML_ENABLE_SCRIPT_SUPPORT=OFF
$(PKG)_REBUILD_SUBOPTS += FREETZ_TARGET_IPV6_SUPPORT

$(PKG_SOURCE_DOWNLOAD)
$(PKG_UNPACKED)
$(PKG_CONFIGURED_CMAKE)

$($(PKG)_BINARY): $($(PKG)_DIR)/.configured
	$(SUBMAKE) -C $(LIBUPNP_DIR)

$($(PKG)_STAGING_BINARY): $($(PKG)_BINARY)
	$(SUBMAKE) -C $(LIBUPNP_DIR) \
		DESTDIR="$(TARGET_TOOLCHAIN_STAGING_DIR)" \
		install
	@touch $@

$($(PKG)_TARGET_BINARY): $($(PKG)_STAGING_BINARY)
	$(INSTALL_LIBRARY_STRIP_WILDCARD_BEFORE_SO)

$(pkg): $($(PKG)_STAGING_BINARY)

$(pkg)-precompiled: $($(PKG)_TARGET_BINARY)

$(pkg)-clean:
	-$(SUBMAKE) -C $(LIBUPNP_DIR) clean

$(pkg)-uninstall:
	$(RM) $($(PKG)_TARGET_DIR)/libupnp.so*

$(PKG_FINISH)
