$(call PKG_INIT_LIB, 5.7.0)
$(PKG)_LIB_VERSION:=1.2.6
$(PKG)_SOURCE_DOWNLOAD_NAME:=$($(PKG)_VERSION).tar.gz
$(PKG)_SOURCE:=$(pkg)-$($(PKG)_VERSION).tar.gz
$(PKG)_HASH:=c5742ba1054d36ff3d22f0101a9be066f55f6becb9b2a7352c79fa362f2d3d76
$(PKG)_SITE:=https://github.com/dbry/WavPack/archive/refs/tags
### WEBSITE:=https://www.wavpack.com/
### CHANGES:=https://github.com/dbry/WavPack/releases
### CVSREPO:=https://github.com/dbry/WavPack

$(PKG)_BINARY:=$($(PKG)_DIR)/libwavpack.so.$($(PKG)_LIB_VERSION)
$(PKG)_STAGING_BINARY:=$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libwavpack.so.$($(PKG)_LIB_VERSION)
$(PKG)_TARGET_BINARY:=$($(PKG)_TARGET_DIR)/libwavpack.so.$($(PKG)_LIB_VERSION)

$(PKG)_DEPENDS_ON += cmake-host

$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_INSTALL_PREFIX="/usr"
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_BUILD_TYPE=Release
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_SKIP_RPATH=YES
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_SHARED_LIBS=ON
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_TESTING=OFF
$(PKG)_CONFIGURE_OPTIONS += -DWAVPACK_ENABLE_LEGACY=OFF
$(PKG)_CONFIGURE_OPTIONS += -DWAVPACK_ENABLE_ASM=OFF
$(PKG)_CONFIGURE_OPTIONS += -DWAVPACK_INSTALL_DOCS=OFF
$(PKG)_CONFIGURE_OPTIONS += -DWAVPACK_INSTALL_PKGCONFIG_MODULE=ON
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_POLICY_VERSION_MINIMUM=3.5


$(PKG_SOURCE_DOWNLOAD)
$(PKG_UNPACKED)
$(PKG_CONFIGURED_CMAKE)

$($(PKG)_BINARY): $($(PKG)_DIR)/.configured
	$(SUBMAKE) -C $(LIBWAVPACK_DIR)

$($(PKG)_STAGING_BINARY): $($(PKG)_BINARY)
	$(SUBMAKE) -C $(LIBWAVPACK_DIR) \
		DESTDIR="$(TARGET_TOOLCHAIN_STAGING_DIR)" \
		install
	$(PKG_FIX_LIBTOOL_LA) \
		$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/pkgconfig/wavpack.pc
	@touch $@

$($(PKG)_TARGET_BINARY): $($(PKG)_STAGING_BINARY)
	$(INSTALL_LIBRARY_STRIP)

$(pkg): $($(PKG)_STAGING_BINARY)

$(pkg)-precompiled: $($(PKG)_TARGET_BINARY)

$(pkg)-clean:
	-$(SUBMAKE) -C $(LIBWAVPACK_DIR) clean
	$(RM) -r \
		$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/include/wavpack \
		$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libwavpack* \
		$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/pkgconfig/wavpack.pc

$(pkg)-uninstall:
	$(RM) $(LIBWAVPACK_TARGET_DIR)/libwavpack*.so*

$(PKG_FINISH)
