#!/bin/sh

. /usr/lib/libmodcgi.sh

case "$QUERY_STRING" in
  start*)
    ACTION_RESULT="started"
    ;;
  stop*)
    ACTION_RESULT="stopped"
    ;;
esac

[ -r /etc/options.cfg ] && . /etc/options.cfg

check "$TTYD_READONLY" "yes:readonly" "*:readwrite"

sec_begin "$(lang de:"Starttyp" en:"Start type")"
cgi_print_radiogroup_service_starttype "enabled" "$TTYD_ENABLED" "" "" 0
sec_end

sec_begin "$(lang de:"Konfiguration" en:"Configuration")"
cat << 'CFGCSS'
<style>
.ttyd-cfg-tbl{width:100%;border-collapse:collapse;}
.ttyd-cfg-tbl td{vertical-align:top;padding:3px 6px;word-break:break-word;}
.ttyd-cfg-tbl td:first-child{white-space:nowrap;width:1%;padding-right:10px;}
.ttyd-cfg-tbl input[type=text],.ttyd-cfg-tbl input[type=password]{max-width:100%;width:100%;box-sizing:border-box;}
.ttyd-cfg-tbl input[type=checkbox]{width:auto;}
.ttyd-cfg-tbl small{font-size:.8em;word-break:break-word;overflow-wrap:anywhere;}
@media(max-width:620px){
  .ttyd-cfg-tbl,.ttyd-cfg-tbl tbody,.ttyd-cfg-tbl tr,.ttyd-cfg-tbl td{display:block;width:100%!important;}
  .ttyd-cfg-tbl td:first-child{white-space:normal;padding-bottom:2px;font-weight:600;}
  .ttyd-cfg-tbl tr{margin-bottom:8px;padding-bottom:6px;border-bottom:1px solid var(--evo-border,#444);}
}
</style>
CFGCSS
cat << EOF
<table class="ttyd-cfg-tbl">
<tr>
<td><i>$(lang de:"Port:" en:"Port:")</i></td>
<td><input type="text" name="port" maxlength="5" value="$(html "$TTYD_PORT")"></td>
<td><small>$(lang de:"Standard: 7681" en:"Default: 7681")</small></td>
</tr>
<tr>
<td><i>$(lang de:"Port-Schutz:" en:"Port protection:")</i></td>
<td><input type="password" name="credential" value="$(html "$TTYD_CREDENTIAL")" autocomplete="off"></td>
<td><small>$(lang de:"benutzer:passwort f&uuml;r direkten Browser-Zugriff auf http://fritz.box:$TTYD_PORT/ (leer = kein Passwort; das eingebettete Web-Terminal ben&ouml;tigt keinen Eintrag)" en:"user:password for direct browser access to http://fritz.box:$TTYD_PORT/ (blank = no ttyd auth; the embedded web terminal does not use this)")</small></td>
</tr>
<tr>
<td><i>$(lang de:"Nur lesen:" en:"Read-only:")</i></td>
<td><input type="checkbox" name="readonly" value="yes"$readonly_chk></td>
<td><small>$(lang de:"Eingaben vom Client ignorieren" en:"Disable input from clients")</small></td>
</tr>
<tr>
<td><i>$(lang de:"Shell-Befehl:" en:"Shell command:")</i></td>
<td><input type="text" name="cmd" value="$(html "$TTYD_CMD")"></td>
<td><small>$(lang de:"/usr/bin/ttyd-shell = per-Boot-Token-Schutz + auto-Login als root &uuml;ber Web-UI; alternativ /bin/login f&uuml;r Passwortabfrage" en:"/usr/bin/ttyd-shell = per-boot token auth + auto root login via web UI; or /bin/login to require password")</small></td>
</tr>
<tr>
<td><i>$(lang de:"Umgebung:" en:"Environment:")</i></td>
<td colspan="2"><input type="text" name="env" value="$(html "$TTYD_ENV")"></td>
</tr>
<tr>
<td colspan="3"><small>$(lang de:"Umgebungsvariablen f&uuml;r die Shell, z.B.: LANG=de_DE.UTF-8 TZ=Europe/Berlin" en:"Shell environment variables, e.g.: LANG=de_DE.UTF-8 TZ=Europe/Berlin")</small></td>
</tr>
<tr>
<td><i>$(lang de:"Weitere Optionen:" en:"Extra options:")</i></td>
<td colspan="2"><input type="text" name="args" value="$(html "$TTYD_ARGS")"></td>
</tr>
</table>
EOF
sec_end

# Read per-boot token generated by rc.ttyd (used by ttyd-shell wrapper).
# Embed in the page so the browser auto-submits on connect.
TTYD_TOKEN=$(cat /var/run/ttyd.token 2>/dev/null)

# Only render the Web Terminal section when ttyd is actually running
if pidof ttyd >/dev/null 2>&1; then

sec_begin "$(lang de:"Web-Terminal" en:"Web Terminal")"

cat << EOF
<div id="ttyd-wrap">
  <div id="ttyd-proxy-banner" style="display:none;padding:28px 20px;text-align:center;background:#1e1e1e;">
    <p style="margin:0 0 16px;color:#aaa;font-size:.9em">$(lang de:"Sitzung l&auml;uft &uuml;ber den HTTPS-Proxy &mdash; WebSocket wird als <em>Mixed&nbsp;Content</em> blockiert." en:"Session is running via the HTTPS proxy &mdash; WebSocket is blocked as <em>mixed&nbsp;content</em>.")</p>
    <a id="ttyd-open-btn" href="#" target="_blank" style="display:inline-block;padding:10px 24px;background:#0e9078;color:#fff;border-radius:4px;text-decoration:none;font-size:.95em;font-weight:600;">$(lang de:"Web-Terminal in neuem Tab &ouml;ffnen &nbsp;&#x2197;" en:"Open Web Terminal in new tab &nbsp;&#x2197;")</a>
  </div>
  <div id="ttyd-direct">
  <div id="ttyd-toolbar">
    <span id="ttyd-status" class="ttyd-disc">&#x25cf; $(lang de:"Getrennt" en:"Disconnected")</span>
    <span class="ttyd-filler"></span>
    <select id="ttyd-theme-sel" onchange="ttydSetTheme(this.value)" title="$(lang de:"Farbschema" en:"Colour theme")">
      <option value="dark">$(lang de:"Dunkel" en:"Dark")</option>
      <option value="freetz">Freetz EVO</option>
      <option value="green">Green on Black</option>
      <option value="amber">Amber</option>
      <option value="solarized-dark">Solarized Dark</option>
      <option value="solarized-light">Solarized Light</option>
      <option value="light">$(lang de:"Hell" en:"Light")</option>
    </select>
    <button type="button" onclick="ttydFontDelta(-1)" title="$(lang de:"Schrift kleiner" en:"Decrease font size")">A&#x2212;</button>
    <button type="button" onclick="ttydFontDelta(1)"  title="$(lang de:"Schrift gr&#246;&#223;er" en:"Increase font size")">A+</button>
    <button type="button" onclick="ttydToggleSearch()" title="$(lang de:"Suchen" en:"Search")">&#x2315;</button>
    <button type="button" onclick="ttydReconnect()" title="$(lang de:"Neu verbinden" en:"Reconnect")">&#x21BA;</button>
    <button type="button" id="ttyd-fs-btn" onclick="ttydToggleFullscreen()" title="$(lang de:"Vollbild" en:"Fullscreen (Esc to exit)")">&#x26F6;</button>
    <a href="/ttyd/evo-terminal.html?port=$(html "${TTYD_PORT:-7681}")&tok=$(html "$TTYD_TOKEN")" target="_blank" id="ttyd-ext-link" title="$(lang de:"In neuem Tab &#246;ffnen" en:"Open full-screen terminal in new tab")">&#x2197;</a>
  </div>
  <div id="ttyd-search-bar" style="display:none">
    <input type="text" id="ttyd-search-inp" placeholder="$(lang de:"Suchen..." en:"Search...")"
           oninput="ttydSearchNow()" onkeydown="if(event.key==='Enter'){ttydSearchNext();}else if(event.key==='Escape'){ttydCloseSearch();}">
    <button type="button" onclick="ttydSearchPrev()" title="$(lang de:"Vorheriges" en:"Previous")">&#9664;</button>
    <button type="button" onclick="ttydSearchNext()" title="$(lang de:"N&#228;chstes" en:"Next")">&#9654;</button>
    <button type="button" onclick="ttydCloseSearch()" title="$(lang de:"Schlie&#223;en" en:"Close")">&#x2715;</button>
  </div>
  <div id="ttyd-term"></div>
  </div><!-- #ttyd-direct -->
</div>
<script>var TTYD_CFG={port:$(html "${TTYD_PORT:-7681}"),tok:"$(html "$TTYD_TOKEN")",webport:$(html "${SERVER_PORT:-81}")};</script>
EOF

cat << 'CSSEOF'
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@xterm/xterm@5/css/xterm.css">
<style>
#ttyd-wrap{position:relative;border:1px solid #555;border-radius:4px;overflow:hidden;margin:8px 0;background:#1e1e1e;}
#ttyd-toolbar{display:flex;align-items:center;gap:5px;padding:5px 8px;background:#2d2d2d;border-bottom:1px solid #444;flex-wrap:wrap;}
.ttyd-filler{flex:1}
#ttyd-toolbar button,#ttyd-toolbar select{font-size:12px;padding:2px 7px;cursor:pointer;background:#3a3a3a;color:#ddd;border:1px solid #555;border-radius:3px;}
#ttyd-toolbar button:hover,#ttyd-toolbar select:hover{background:#505050;}
.ttyd-conn{color:#4caf50;font-size:12px;white-space:nowrap;}
.ttyd-prog{color:#ff9800;font-size:12px;white-space:nowrap;}
.ttyd-disc{color:#f44336;font-size:12px;white-space:nowrap;}
#ttyd-search-bar{display:none;align-items:center;gap:4px;padding:4px 8px;background:#2d2d2d;border-bottom:1px solid #444;}
#ttyd-search-inp{flex:1;font-size:12px;padding:2px 6px;background:#3a3a3a;color:#ddd;border:1px solid #555;border-radius:3px;}
#ttyd-search-bar button{font-size:12px;padding:2px 6px;cursor:pointer;background:#3a3a3a;color:#ddd;border:1px solid #555;border-radius:3px;}
#ttyd-search-bar button:hover{background:#505050;}
#ttyd-term{width:100%;height:460px;padding:4px;box-sizing:border-box;}
#ttyd-wrap.ttyd-fs{position:fixed!important;top:0;left:0;right:0;bottom:0;width:100vw!important;height:100vh!important;z-index:9999;border-radius:0;margin:0;}
#ttyd-wrap.ttyd-fs #ttyd-term{height:calc(100vh - 38px)!important;}
.xterm,.xterm-viewport{height:100%!important;}
.xterm-viewport{overflow-y:auto!important;}
#ttyd-ext-link{font-size:12px;padding:2px 7px;text-decoration:none;display:inline-flex;align-items:center;background:#3a3a3a;color:#ddd;border:1px solid #555;border-radius:3px;}
#ttyd-ext-link:hover{background:#505050;}
</style>
CSSEOF

cat << 'JSEOF'
<script src="https://cdn.jsdelivr.net/npm/@xterm/xterm@5/lib/xterm.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@xterm/addon-fit@0/lib/addon-fit.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@xterm/addon-web-links@0/lib/addon-web-links.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@xterm/addon-search@0/lib/addon-search.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@xterm/addon-unicode11@0/lib/addon-unicode11.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@xterm/addon-canvas@0/lib/addon-canvas.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@xterm/addon-webgl@0/lib/addon-webgl.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@xterm/addon-clipboard@0/lib/addon-clipboard.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@xterm/addon-progress@0/lib/addon-progress.js"></script>
<script>
(function(){
'use strict';

/* ── Themes ───────────────────────────────────────────────────── */
var TH = {
  dark: {background:'#1e1e1e',foreground:'#d4d4d4',cursor:'#aeafad',cursorAccent:'#1e1e1e',
    selectionBackground:'rgba(255,255,255,.15)',
    black:'#000',red:'#cd3131',green:'#0dbc79',yellow:'#e5e510',blue:'#2472c8',
    magenta:'#bc3fbc',cyan:'#11a8cd',white:'#e5e5e5',
    brightBlack:'#666',brightRed:'#f14c4c',brightGreen:'#23d18b',brightYellow:'#f5f543',
    brightBlue:'#3b8eea',brightMagenta:'#d670d6',brightCyan:'#29b8db',brightWhite:'#e5e5e5'},
  freetz: {background:'#0d1117',foreground:'#c9d1d9',cursor:'#3b82f6',cursorAccent:'#0d1117',
    selectionBackground:'rgba(59,130,246,.3)',
    black:'#21262d',red:'#f85149',green:'#56d364',yellow:'#e3b341',blue:'#58a6ff',
    magenta:'#d2a8ff',cyan:'#76e3ea',white:'#b1bac4',
    brightBlack:'#6e7681',brightRed:'#ff7b72',brightGreen:'#3fb950',brightYellow:'#d29922',
    brightBlue:'#79c0ff',brightMagenta:'#d2a8ff',brightCyan:'#56d4dd',brightWhite:'#f0f6fc'},
  green: {background:'#000',foreground:'#33ff33',cursor:'#33ff33',cursorAccent:'#000',
    selectionBackground:'rgba(51,255,51,.25)',
    black:'#000',red:'#c00',green:'#33ff33',yellow:'#cc0',blue:'#00c',
    magenta:'#c0c',cyan:'#0cc',white:'#ccc',
    brightBlack:'#555',brightRed:'#f33',brightGreen:'#6f6',brightYellow:'#ff5',
    brightBlue:'#55f',brightMagenta:'#f5f',brightCyan:'#5ff',brightWhite:'#fff'},
  amber: {background:'#0c0800',foreground:'#ffb000',cursor:'#ffb000',cursorAccent:'#0c0800',
    selectionBackground:'rgba(255,176,0,.25)',
    black:'#0c0800',red:'#dd2222',green:'#aa0',yellow:'#ffb000',blue:'#550',
    magenta:'#a50',cyan:'#a70',white:'#ffb000',
    brightBlack:'#550',brightRed:'#f55',brightGreen:'#dd0',brightYellow:'#fd0',
    brightBlue:'#770',brightMagenta:'#f80',brightCyan:'#fc0',brightWhite:'#fe8'},
  'solarized-dark': {background:'#002b36',foreground:'#839496',cursor:'#93a1a1',cursorAccent:'#002b36',
    selectionBackground:'rgba(147,161,161,.25)',
    black:'#073642',red:'#dc322f',green:'#859900',yellow:'#b58900',blue:'#268bd2',
    magenta:'#d33682',cyan:'#2aa198',white:'#eee8d5',
    brightBlack:'#002b36',brightRed:'#cb4b16',brightGreen:'#586e75',brightYellow:'#657b83',
    brightBlue:'#839496',brightMagenta:'#6c71c4',brightCyan:'#93a1a1',brightWhite:'#fdf6e3'},
  'solarized-light': {background:'#fdf6e3',foreground:'#657b83',cursor:'#586e75',cursorAccent:'#fdf6e3',
    selectionBackground:'rgba(88,110,117,.2)',
    black:'#073642',red:'#dc322f',green:'#859900',yellow:'#b58900',blue:'#268bd2',
    magenta:'#d33682',cyan:'#2aa198',white:'#eee8d5',
    brightBlack:'#002b36',brightRed:'#cb4b16',brightGreen:'#586e75',brightYellow:'#657b83',
    brightBlue:'#839496',brightMagenta:'#6c71c4',brightCyan:'#93a1a1',brightWhite:'#fdf6e3'},
  light: {background:'#f5f7fb',foreground:'#1e293b',cursor:'#3b82f6',cursorAccent:'#f5f7fb',
    selectionBackground:'rgba(59,130,246,.2)',
    black:'#1e293b',red:'#b91c1c',green:'#15803d',yellow:'#b45309',blue:'#1d4ed8',
    magenta:'#7e22ce',cyan:'#0e7490',white:'#94a3b8',
    brightBlack:'#475569',brightRed:'#ef4444',brightGreen:'#22c55e',brightYellow:'#f59e0b',
    brightBlue:'#3b82f6',brightMagenta:'#a855f7',brightCyan:'#06b6d4',brightWhite:'#f1f5f9'}
};

/* ── State ────────────────────────────────────────────────────── */
var term = null, fitAddon = null, searchAddon = null, ws = null;
var fontSize = 14, curTheme = 'dark';

/* ── Status helper ────────────────────────────────────────────── */
function setStatus(cls, msg) {
  var el = document.getElementById('ttyd-status');
  if (!el) return;
  el.className = cls;
  el.textContent = '\u25cf ' + msg;
}

/* ── Init terminal ────────────────────────────────────────────── */
function initTerm(theme, size) {
  var el = document.getElementById('ttyd-term');
  if (!el) return;
  if (term) { try { term.dispose(); } catch(e) {} term = null; }
  el.innerHTML = '';

  var t = new Terminal({
    theme: TH[theme] || TH.dark,
    fontSize: size || 14,
    fontFamily: "'Cascadia Code','Fira Code','JetBrains Mono','Consolas',monospace",
    fontWeight: '400',
    lineHeight: 1.18,
    cursorBlink: true,
    cursorStyle: 'block',
    scrollback: 10000,
    allowProposedApi: true,
    convertEol: false
  });

  fitAddon = new FitAddon.FitAddon();
  t.loadAddon(fitAddon);

  try { t.loadAddon(new WebLinksAddon.WebLinksAddon()); } catch(e) {}

  searchAddon = null;
  try { searchAddon = new SearchAddon.SearchAddon(); t.loadAddon(searchAddon); } catch(e) {}

  try {
    var u11 = new Unicode11Addon.Unicode11Addon();
    t.loadAddon(u11);
    t.unicode.activeVersion = '11';
  } catch(e) {}

  var rendered = false;
  try {
    var wgl = new WebglAddon.WebglAddon();
    wgl.onContextLoss(function() { wgl.dispose(); });
    t.loadAddon(wgl);
    rendered = true;
  } catch(e) {}
  if (!rendered) {
    try { t.loadAddon(new CanvasAddon.CanvasAddon()); } catch(e) {}
  }

  try { t.loadAddon(new ClipboardAddon.ClipboardAddon()); } catch(e) {}
  try { t.loadAddon(new ProgressAddon.ProgressAddon()); } catch(e) {}

  t.open(el);
  fitAddon.fit();

  /* send keyboard input to ttyd */
  t.onData(function(d) {
    if (ws && ws.readyState === WebSocket.OPEN) ws.send('0' + d);
  });

  /* notify ttyd of resize */
  t.onResize(function(sz) {
    if (ws && ws.readyState === WebSocket.OPEN)
      ws.send('1' + JSON.stringify({columns: sz.cols, rows: sz.rows}));
  });

  /* update container background */
  var bg = (TH[theme] || TH.dark).background;
  document.getElementById('ttyd-wrap').style.background = bg;

  term = t;
  curTheme = theme;
  fontSize = size || 14;
}

/* ── Connect to ttyd ──────────────────────────────────────────── */
function ttydConnect() {
  var host = window.location.hostname;
  var port = (TTYD_CFG && TTYD_CFG.port) ? TTYD_CFG.port : 7681;

  var url  = 'ws://' + host + ':' + port + '/ws';

  setStatus('ttyd-prog', 'Connecting to ' + host + ':' + port + '...');

  if (ws) { try { ws.close(); } catch(e) {} ws = null; }

  ws = new WebSocket(url, ['tty']);
  ws.binaryType = 'arraybuffer';

  ws.onopen = function() {
    setStatus('ttyd-conn', 'Connected \u00b7 ' + host + ':' + port);
    if (term) { term.focus(); fitAddon.fit(); }
    /* ttyd protocol: client must send JSON_DATA immediately on open.
       The server does NOT send an auth challenge over WS — it sends binary
       command frames (title, prefs) right away.  We send auth first so the
       server can spawn the process.  With no -c flag the token is empty. */
    ws.send(JSON.stringify({
      AuthToken: '',
      columns: term ? term.cols : 80,
      rows:    term ? term.rows : 24
    }));
    /* auto-submit per-boot token to the ttyd-shell wrapper;
       arrives as first PTY input after spawn_process, invisible to the user */
    if (TTYD_CFG.tok) ws.send('0' + TTYD_CFG.tok + '\n');
  };

  ws.onmessage = function(ev) {
    /* All post-open messages from ttyd are binary ArrayBuffers:
       byte[0] = command, rest = payload.
       Pass OUTPUT payload as Uint8Array so xterm handles encoding itself
       (avoids TextDecoder corrupting non-UTF-8 terminal byte sequences). */
    var bytes = (ev.data instanceof ArrayBuffer)
      ? new Uint8Array(ev.data)
      : (function(s){ var b=new Uint8Array(s.length); for(var i=0;i<s.length;i++) b[i]=s.charCodeAt(i)&0xff; return b; })(ev.data);

    if (!bytes.length) return;
    var cmd = bytes[0];

    if (cmd === 48 /* '0' = OUTPUT */) {
      if (term) term.write(bytes.subarray(1));
    } else if (cmd === 49 /* '1' = SET_WINDOW_TITLE */) {
      /* title update — ignore */
    } else if (cmd === 50 /* '2' = SET_PREFERENCES */) {
      /* server prefs — we manage our own theme, ignore */
    }
  };

  ws.onclose = function(ev) {
    var why = ev.wasClean
      ? 'Closed (code ' + ev.code + ')'
      : 'Lost connection. Is ttyd running on port ' + port + '?';
    setStatus('ttyd-disc', why);
    if (term) term.writeln('\r\n\x1b[31m[ ' + why + ' ]\x1b[0m');
  };

  ws.onerror = function() {
    setStatus('ttyd-disc', 'Error — check that ttyd is enabled and started.');
  };
}

/* ── Public helpers (called from inline onclick) ──────────────── */
window.ttydReconnect = function() {
  if (term) term.clear();
  ttydConnect();
};

window.ttydSetTheme = function(name) {
  curTheme = name;
  if (!term) return;
  term.options.theme = TH[name] || TH.dark;
  var bg = (TH[name] || TH.dark).background;
  document.getElementById('ttyd-wrap').style.background = bg;
};

window.ttydFontDelta = function(d) {
  fontSize = Math.max(8, Math.min(24, fontSize + d));
  if (term) { term.options.fontSize = fontSize; fitAddon.fit(); }
};

window.ttydToggleFullscreen = function() {
  var w = document.getElementById('ttyd-wrap');
  var b = document.getElementById('ttyd-fs-btn');
  if (w.classList.contains('ttyd-fs')) {
    w.classList.remove('ttyd-fs');
    b.innerHTML = '&#x26F6;';
    b.title = 'Fullscreen (Esc to exit)';
  } else {
    w.classList.add('ttyd-fs');
    b.innerHTML = '&#x2715;';
    b.title = 'Exit Fullscreen';
  }
  setTimeout(function() { if (fitAddon) fitAddon.fit(); }, 80);
};

window.ttydToggleSearch = function() {
  var bar = document.getElementById('ttyd-search-bar');
  if (bar.style.display === 'none' || !bar.style.display) {
    bar.style.display = 'flex';
    document.getElementById('ttyd-search-inp').focus();
  } else {
    ttydCloseSearch();
  }
};

window.ttydCloseSearch = function() {
  document.getElementById('ttyd-search-bar').style.display = 'none';
  if (searchAddon) searchAddon.clearDecorations();
  if (term) term.focus();
};

window.ttydSearchNow = function() {
  if (!searchAddon) return;
  var v = document.getElementById('ttyd-search-inp').value;
  if (v) searchAddon.findNext(v, {decorations:{
    matchBackground:'#ffd70066',matchBorder:'#ffa500',matchOverviewRuler:'#ffd700',
    activeMatchBackground:'#ff6600cc',activeMatchBorder:'#ff4400',activeMatchColorOverviewRuler:'#ff6600'
  }});
};

window.ttydSearchNext = function() {
  if (!searchAddon) return;
  var v = document.getElementById('ttyd-search-inp').value;
  if (v) searchAddon.findNext(v);
};

window.ttydSearchPrev = function() {
  if (!searchAddon) return;
  var v = document.getElementById('ttyd-search-inp').value;
  if (v) searchAddon.findPrevious(v);
};

/* ── Keyboard shortcuts ───────────────────────────────────────── */
document.addEventListener('keydown', function(e) {
  /* Esc → exit fullscreen if active */
  if (e.key === 'Escape') {
    var w = document.getElementById('ttyd-wrap');
    if (w && w.classList.contains('ttyd-fs')) { ttydToggleFullscreen(); e.preventDefault(); }
  }
});

/* ── Window resize ────────────────────────────────────────────── */
var _rft;
window.addEventListener('resize', function() {
  clearTimeout(_rft);
  _rft = setTimeout(function() { if (fitAddon) fitAddon.fit(); }, 80);
});

/* ── Bootstrap ────────────────────────────────────────────────── */
(function(){
  var isProxy = window.location.protocol === 'https:';
  var port    = (TTYD_CFG && TTYD_CFG.port)    ? TTYD_CFG.port    : 7681;
  var wport   = (TTYD_CFG && TTYD_CFG.webport) ? TTYD_CFG.webport : 81;
  var tok     = (TTYD_CFG && TTYD_CFG.tok)     ? TTYD_CFG.tok     : '';
  var host    = window.location.hostname;
  var extUrl  = 'http://' + host + ':' + wport +
                '/ttyd/evo-terminal.html?port=' + port +
                (tok ? '&tok=' + encodeURIComponent(tok) : '');

  /* always keep the "open in tab" arrow link up to date */
  var extLink = document.getElementById('ttyd-ext-link');
  if (extLink) extLink.href = extUrl;

  if (isProxy) {
    /* HTTPS proxy session: show open-button, hide xterm UI */
    var btn = document.getElementById('ttyd-open-btn');
    if (btn) btn.href = extUrl;
    var banner = document.getElementById('ttyd-proxy-banner');
    if (banner) banner.style.display = '';
    var direct = document.getElementById('ttyd-direct');
    if (direct) direct.style.display = 'none';
  } else {
    /* Direct HTTP session: initialize xterm and connect */
    initTerm(curTheme, fontSize);
    if (term) term.writeln('\x1b[2mttyd web terminal \u2014 connecting\u2026\x1b[0m');
    ttydConnect();
  }
})();

})();
</script>
JSEOF

if [ -n "$ACTION_RESULT" ]; then
  cat << EOF
<script>
(function() {
  if (window.history && window.history.replaceState) {
    var cleanUrl = window.location.pathname;
    window.history.replaceState({}, document.title, cleanUrl);
  }
})();
</script>
EOF
fi

sec_end

fi  # ttyd running
