#!/bin/sh
# Pi-hole gravity.sh - Download and compile blocklists for dnsmasq
# Adapted for freetz-ng
#
# This script downloads blocklists from configured URLs, processes them
# into a dnsmasq-compatible format, and reloads dnsmasq.

set -e

# Source configuration
[ -r /mod/etc/conf/pi-hole.cfg ] && . /mod/etc/conf/pi-hole.cfg

# Default values
: "${PIHOLE_BLOCKLIST_DIR:=/tmp/flash/pi-hole}"
: "${PIHOLE_BLOCKLIST_URLS:="https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"}"
: "${PIHOLE_DNSMASQ_CONF_DIR:=/tmp/flash/dnsmasq}"
: "${PIHOLE_LOG_FILE:=/var/log/pi-hole.log}"
: "${PIHOLE_GRAVITY_DB:=/tmp/flash/pi-hole/gravity.db}"

BLOCKLIST_FILE="${PIHOLE_BLOCKLIST_DIR}/blocklist.txt"
BLOCKLIST_COUNT=0

log() {
	local level="$1"
	shift
	echo "$(date): [${level}] $*" >> "${PIHOLE_LOG_FILE}"
}

log_info() { log "INFO" "$@"; }
log_err() { log "ERROR" "$@" >&2; }

# Create required directories
mkdir -p "${PIHOLE_BLOCKLIST_DIR}" "${PIHOLE_DNSMASQ_CONF_DIR}" 2>/dev/null

log_info "Starting gravity blocklist update..."

# Process each blocklist URL
IFS=' '
for url in ${PIHOLE_BLOCKLIST_URLS}; do
	[ -z "$url" ] && continue
	url="$(echo "$url" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
	[ -z "$url" ] && continue
	
	log_info "Downloading blocklist: ${url}"
	
	TEMP_FILE=$(mktemp -t gravity.XXXXXX)
	
	# Download with curl (preferred) or wget
	if command -v curl >/dev/null 2>&1; then
		curl -s -L --max-time 60 --retry 3 "$url" > "$TEMP_FILE" 2>/dev/null
	elif command -v wget >/dev/null 2>&1; then
		wget -q -O "$TEMP_FILE" --timeout=60 --tries=3 "$url" 2>/dev/null
	fi
	
	if [ ! -s "$TEMP_FILE" ]; then
		log_err "Failed to download: ${url}"
		rm -f "$TEMP_FILE"
		continue
	fi
	
	# Process: extract hostnames, strip comments, skip IPs, remove whitespace
	# Pi-hole standard format: 0.0.0.0 domain.com or 127.0.0.1 domain.com
	# Also handle plain domain lists (one per line)
	# Convert to: 0.0.0.0 domain.com format for dnsmasq
	processed=$(mktemp -t gravity_proc.XXXXXX)
	
	# Extract IP-based entries
	grep -v '^#' "$TEMP_FILE" | \
		grep -v '^[[:space:]]*$' | \
		grep -E '^(0\.0\.0\.0|127\.0\.0\.1|[[:space:]]*::1?)' | \
		awk '{print $2}' | \
		grep -v '^localhost$' | \
		grep -v '^broadcasthost$' | \
		grep -v '^local$' | \
		grep -v '^[[:space:]]*$' | \
		grep -v '^\.[[:space:]]*$' | \
		sort -u > "$processed" 2>/dev/null
	
	# Also handle plain domain lists (one domain per line, no IP prefix)
	grep -v '^#' "$TEMP_FILE" | \
		grep -v '^[[:space:]]*$' | \
		grep -v -E '^(0\.0\.0\.0|127\.0\.0\.1|[[:space:]]*::1?)' | \
		grep -v '[[:space:]]' | \
		grep '\.' | \
		grep -v '^localhost$' | \
		grep -v '^[[:space:]]*$' | \
		sort -u >> "$processed" 2>/dev/null
	
	rm -f "$TEMP_FILE"
	
	# Append to combined blocklist
	if [ -s "$processed" ]; then
		count=$(wc -l < "$processed")
		cat "$processed" >> "$BLOCKLIST_FILE" 2>/dev/null
		BLOCKLIST_COUNT=$((BLOCKLIST_COUNT + count))
		log_info "Added ${count} domains from: ${url}"
	fi
	rm -f "$processed"
done

# Sort and deduplicate the combined blocklist
if [ -f "$BLOCKLIST_FILE" ] && [ -s "$BLOCKLIST_FILE" ]; then
	sort -u "$BLOCKLIST_FILE" > "${BLOCKLIST_FILE}.tmp" 2>/dev/null
	mv "${BLOCKLIST_FILE}.tmp" "$BLOCKLIST_FILE"
	TOTAL=$(wc -l < "$BLOCKLIST_FILE")
	log_info "Total unique blocked domains: ${TOTAL}"
fi

# Generate dnsmasq-compatible configuration
# dnsmasq can use: addn-hosts=/path/to/hosts or conf-file=/path/to/conf
# We generate a hosts file for addn-hosts
{
	echo "# Pi-hole blocklist - generated by gravity.sh"
	echo "# ${TOTAL:-0} domains blocked"
	echo "# Last updated: $(date)"
	
	if [ -f "$BLOCKLIST_FILE" ]; then
		while IFS= read -r domain; do
			[ -z "$domain" ] && continue
			echo "0.0.0.0 ${domain}"
		done < "$BLOCKLIST_FILE"
	fi
} > "${PIHOLE_DNSMASQ_CONF_DIR}/pi-hole.hosts" 2>/dev/null

# Signal dnsmasq to reload
if pidof dnsmasq >/dev/null 2>&1; then
	log_info "Reloading dnsmasq..."
	killall -HUP dnsmasq 2>/dev/null || true
fi

log_info "Gravity update completed (${BLOCKLIST_COUNT} domains added)"
echo "${BLOCKLIST_COUNT}"
