$(call PKG_INIT_LIB, 0.1.3)
# Project version 0.1.3, library SO version 0.1.2
$(PKG)_LIB_VERSION:=0.1.2
$(PKG)_SOURCE:=soxr-$($(PKG)_VERSION)-Source.tar.xz
$(PKG)_HASH:=b111c15fdc8c029989330ff559184198c161100a59312f5dc19ddeb9b5a15889
$(PKG)_SITE:=https://sourceforge.net/projects/soxr/files
### WEBSITE:=https://sourceforge.net/projects/soxr/

$(PKG)_CATEGORY_LIBS:=Multimedia##Audio codecs
$(PKG)_BINARY:=$($(PKG)_DIR)/src/libsoxr.so.$($(PKG)_LIB_VERSION)
$(PKG)_STAGING_BINARY:=$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libsoxr.so.$($(PKG)_LIB_VERSION)
$(PKG)_TARGET_BINARY:=$($(PKG)_TARGET_DIR)/libsoxr.so.$($(PKG)_LIB_VERSION)

$(PKG)_DEPENDS_ON += cmake-host

$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_INSTALL_PREFIX="/usr"
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_BUILD_TYPE=Release
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_SKIP_RPATH=YES
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_POLICY_VERSION_MINIMUM=3.5
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_SHARED_LIBS=ON
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_TESTS=OFF
$(PKG)_CONFIGURE_OPTIONS += -DWITH_AVFFT=OFF
$(PKG)_CONFIGURE_OPTIONS += -DWITH_OPENMP=OFF
$(PKG)_CONFIGURE_OPTIONS += -DWITH_LSR_BINDINGS=OFF
$(PKG)_CONFIGURE_OPTIONS += -DWITH_CR32=OFF
$(PKG)_CONFIGURE_OPTIONS += -DWITH_CR64=OFF
$(PKG)_CONFIGURE_OPTIONS += -DWITH_HIDDEN_VISIBILITY=OFF

$(PKG_SOURCE_DOWNLOAD)
$(PKG_UNPACKED)
$(PKG_CONFIGURED_CMAKE)

$($(PKG)_BINARY): $($(PKG)_DIR)/.configured
	$(SUBMAKE) -C $(SOXR_DIR)

$($(PKG)_STAGING_BINARY): $($(PKG)_BINARY)
	$(SUBMAKE) -C $(SOXR_DIR) \
		DESTDIR="$(TARGET_TOOLCHAIN_STAGING_DIR)" \
		install
	@touch $@

$($(PKG)_TARGET_BINARY): $($(PKG)_STAGING_BINARY)
	$(INSTALL_LIBRARY_STRIP)

$(pkg): $($(PKG)_STAGING_BINARY)

$(pkg)-precompiled: $($(PKG)_TARGET_BINARY)

$(pkg)-clean:
	-$(SUBMAKE) -C $(SOXR_DIR) clean

$(pkg)-uninstall:
	$(RM) $($(PKG)_TARGET_DIR)/libsoxr.so*

$(PKG_FINISH)
