$(call PKG_INIT_LIB, 1.2.2)
# Project version 1.2.2, library SONAME version 1.0.37
$(PKG)_LIB_VERSION:=1.0.37
$(PKG)_SOURCE_DOWNLOAD_NAME:=$($(PKG)_VERSION).tar.gz
$(PKG)_SOURCE:=libsndfile-$($(PKG)_VERSION).tar.gz
$(PKG)_HASH:=ffe12ef8add3eaca876f04087734e6e8e029350082f3251f565fa9da55b52121
$(PKG)_SITE:=https://github.com/libsndfile/libsndfile/archive/refs/tags
### WEBSITE:=https://libsndfile.github.io/libsndfile/

$(PKG)_CATEGORY_LIBS:=Multimedia##Audio codecs
$(PKG)_BINARY:=$($(PKG)_DIR)/libsndfile.so.$($(PKG)_LIB_VERSION)
$(PKG)_STAGING_BINARY:=$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libsndfile.so.$($(PKG)_LIB_VERSION)
$(PKG)_TARGET_BINARY:=$($(PKG)_TARGET_DIR)/libsndfile.so.$($(PKG)_LIB_VERSION)

$(PKG)_DEPENDS_ON += cmake-host

$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_INSTALL_PREFIX="/usr"
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_BUILD_TYPE=Release
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_SKIP_RPATH=YES
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_POLICY_VERSION_MINIMUM=3.5
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_SHARED_LIBS=ON
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_PROGRAMS=OFF
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_EXAMPLES=OFF
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_TESTING=OFF
$(PKG)_CONFIGURE_OPTIONS += -DENABLE_EXTERNAL_LIBS=OFF
$(PKG)_CONFIGURE_OPTIONS += -DENABLE_MPEG=OFF

$(PKG_SOURCE_DOWNLOAD)
$(PKG_UNPACKED)
$(PKG_CONFIGURED_CMAKE)

$($(PKG)_BINARY): $($(PKG)_DIR)/.configured
	$(SUBMAKE) -C $(LIBSNDFILE_DIR)

$($(PKG)_STAGING_BINARY): $($(PKG)_BINARY)
	$(SUBMAKE) -C $(LIBSNDFILE_DIR) \
		DESTDIR="$(TARGET_TOOLCHAIN_STAGING_DIR)" \
		install
	@touch $@

$($(PKG)_TARGET_BINARY): $($(PKG)_STAGING_BINARY)
	$(INSTALL_LIBRARY_STRIP)

$(pkg): $($(PKG)_STAGING_BINARY)

$(pkg)-precompiled: $($(PKG)_TARGET_BINARY)

$(pkg)-clean:
	-$(SUBMAKE) -C $(LIBSNDFILE_DIR) clean

$(pkg)-uninstall:
	$(RM) $($(PKG)_TARGET_DIR)/libsndfile.so*

$(PKG_FINISH)
