$(call PKG_INIT_LIB, 1.11.4)
$(PKG)_LIB_VERSION:=5.5
$(PKG)_SOURCE:=$(pkg)-$($(PKG)_VERSION).tar.gz
$(PKG)_HASH:=82e9f2f2421f9d7c2466bbc3173cd09595a88ea37db0d559a9d0a2dc60dc722e
$(PKG)_SITE:=https://github.com/nih-at/libzip/releases/download/v$($(PKG)_VERSION)
### WEBSITE:=https://libzip.org/
### CHANGES:=https://github.com/nih-at/libzip/releases
### CVSREPO:=https://github.com/nih-at/libzip

$(PKG)_BINARY:=$($(PKG)_DIR)/lib/libzip.so.$($(PKG)_LIB_VERSION)
$(PKG)_STAGING_BINARY:=$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libzip.so.$($(PKG)_LIB_VERSION)
$(PKG)_TARGET_BINARY:=$($(PKG)_TARGET_DIR)/libzip.so.$($(PKG)_LIB_VERSION)

$(PKG)_DEPENDS_ON += cmake-host
$(PKG)_DEPENDS_ON += zlib

$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_INSTALL_PREFIX="/usr"
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_BUILD_TYPE=Release
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_SKIP_RPATH=YES
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_SHARED_LIBS=ON
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_TOOLS=OFF
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_REGRESS=OFF
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_EXAMPLES=OFF
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_DOC=OFF
$(PKG)_CONFIGURE_OPTIONS += -DENABLE_BZIP2=OFF
$(PKG)_CONFIGURE_OPTIONS += -DENABLE_LZMA=OFF
$(PKG)_CONFIGURE_OPTIONS += -DENABLE_ZSTD=OFF
$(PKG)_CONFIGURE_OPTIONS += -DENABLE_OPENSSL=OFF
$(PKG)_CONFIGURE_OPTIONS += -DENABLE_COMMONCRYPTO=OFF
$(PKG)_CONFIGURE_OPTIONS += -DENABLE_GNUTLS=OFF
$(PKG)_CONFIGURE_OPTIONS += -DENABLE_MBEDTLS=OFF
$(PKG)_CONFIGURE_OPTIONS += -DENABLE_FDOPEN=ON

$(PKG_SOURCE_DOWNLOAD)
$(PKG_UNPACKED)
$(PKG_CONFIGURED_CMAKE)

$($(PKG)_BINARY): $($(PKG)_DIR)/.configured
	$(SUBMAKE) -C $(LIBZIP_DIR)

$($(PKG)_STAGING_BINARY): $($(PKG)_BINARY)
	$(SUBMAKE) -C $(LIBZIP_DIR) \
		DESTDIR="$(TARGET_TOOLCHAIN_STAGING_DIR)" \
		install
	@touch $@

$($(PKG)_TARGET_BINARY): $($(PKG)_STAGING_BINARY)
	$(INSTALL_LIBRARY_STRIP_WILDCARD_BEFORE_SO)

$(pkg): $($(PKG)_STAGING_BINARY)

$(pkg)-precompiled: $($(PKG)_TARGET_BINARY)

$(pkg)-clean:
	-$(SUBMAKE) -C $(LIBZIP_DIR) clean

$(pkg)-uninstall:
	$(RM) $($(PKG)_TARGET_DIR)/libzip.so*

$(PKG_FINISH)
